### PR TITLE
recover use graphLock when mount a layer

### PR DESCRIPTION
**Pull request by zvier**
Related to: #693

Signed-off-by: Jeff Zvier <zvier20@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@saschagrunert @nalind @vrothberg @giuseppe PTAL

**Comment by nalind** [comment]
LGTM, thanks!

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
do we need a new release?

**Comment by rhatdan** [comment]
https://github.com/containers/storage/releases/tag/v1.23.1

**Pull request merged**
