### PR TITLE
Bump to 1.12.3

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Will merge once this passes tests.

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tests.

**Comment by rhatdan** [comment]
Merging.

**Comment by vrothberg** [comment]
Late to the game but LGTM :+1:

**Pull request merged**
