### PR TITLE
cirrus: Add retry/timeout function for apt-get

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@rhatdan PTAL, this will make working with apt-get **much** less painful.

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@nalind @giuseppe @vrothberg @TomSweeneyRedHat PTAL
This is just for testing, so it will not change functionality.

**Comment by nalind** [comment]
We don't seem to be using much of this yet, so, sure.

**Pull request merged**
