### PR TITLE
dump: handle duplicates

### PR DESCRIPTION
**Pull request by giuseppe**
Add validation for duplicate entries.  Duplicates are ignored, unless there is a mismatch in the values.  In that case, an error is returned.

Also refactor the tests to avoid duplication.
    
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by cgwalters** [comment]
This makes sense to me, but can you explain briefly what motivated the change just for reference?  Did you come across an image in the wild with duplicates?  Were you just thinking through the problem domain?  Is this split out of a different larger pending work PR?

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
> This makes sense to me, but can you explain briefly what motivated the change just for reference? Did you come across an image in the wild with duplicates? Were you just thinking through the problem domain? Is this split out of a different larger pending work PR?

no, I've not encountered yet such case.  I was just looking at ways to make the `dump` code more robust, since most of the issues we had with composefs were caused by the conversion to the dump format

**Pull request merged**
