### PR TITLE
layers: do not try to unmount if not mounted at all on delete

### LINKED ISSUE #233: devmapper regression
See https://github.com/kubernetes-sigs/cri-o/issues/1883 for more information, the range of commits which probably broke devmapper in CRI-O is:

```
# this is the range changed with https://github.com/kubernetes-sigs/cri-o/pull/1814 wihch broke devmapper
git log --oneline --ancestry-path 88d80428f9b146f8f9fe7e2e8cc8688a5aae1a4e..68332c059156eae970a03245cfcd4d717fb66ecd
```

68332c059 Merge pull request #216 from giuseppe/userns-restore-setuid-setgid
2df72f37c chown: restore SUID and SGID bits
1d49427fe Merge pull request #215 from nalind/create-error
2805a4374 layerStore.Put(): always check for Create() errors
02db7cbb0 Merge pull request #214 from nalind/hold-locks
3df3c9f9a Hold the layer store lock while diffing
243c4cd61 Merge pull request #213 from nalind/rolayer-lock
c8670efc1 Fix a lock inversion
d0cb01076 Merge pull request #212 from zmedico/locker-locked-stub-to-lockfile_windows
587b6cc0f Implement Locker.Locked() for windows
9fcbb57eb Merge pull request #210 from zmedico/lock-sanity-checks-for-save-methods
c7ba5749d Add lock sanity checks to Save() methods
17c7d1fee Merge pull request #205 from rhatdan/subuid
ad12a7039 Add more information in errors about missing uidimappings or gidmappings
956a19716 Merge pull request #195 from giuseppe/fuse-overlayfs-shifting
3f55e5a3a shifting: raise an error if the container needs shifting
06cea37b8 tests: add test for shifting support
189739633 drivers: inform Mount of the mappings used by the container
140e0b60e Makefile: install ffjson
883ee15e4 store: use the original image if the driver supports shifting
1e60d8a4c store: include layerID in the error message
9bb1031ef drivers: add new method SupportsShifting() to LayerIDMapUpdater
648024562 overlay: enable support for shifting when FUSE is used
8c814e007 overlay: use full paths to the mount program
9f0144d96 storage.conf: move ostree_repo and skip_mount_home to the correct section
afdedba2d Merge pull request #201 from rhatdan/mountopt
2569af9a0 Fix overlay to handle mountopt properly
7098fdce9 Merge pull request #176 from rhatdan/mount-options
8b1a0f8d6 Add default mount options to pass to drivers
cb8d712f7 Merge pull request #200 from rhatdan/mounted
153897188 Change Mounted to return the number of times mounted
46a8a1cdd Merge pull request #198 from rhatdan/umount
1075a73ca Modify storage to allow callers to determine if a mount point is mounted
124de6810 Merge pull request #199 from giuseppe/allow-to-override-conf-file
e933db596 storage: rename fuse_program to mount_program
759aab13f storage: allow to override .fuse_program from the conf file
c4aa7ad98 store: move configuration file parsing to new function
0ab754169 Merge pull request #197 from TomasTomecek/master
404315aae log errors from ApplyUncompressedLayer
90d0a58ff Merge pull request #194 from rhatdan/contributing
3a5d1ec34 Potential contributors need to find the CONTRIBUTOR information.
9cbb6cb3f Merge pull request #137 from giuseppe/ostree-storage
13af8ce95 tests: add test for ostree deduplication
d33931a3e tests: set mtime to the epoch
c7fdad430 ci: install ostree
85bf5a4b8 Vagrantfile: update to Fedora 28
6c122a294 vagrant: install ostree
f3e7ee3c2 configuration: new option skip_mount_home
52a37816a vfs: add support for ostree deduplication
0c7cb6041 overlay: new option to support ostree deduplication
ffd808a47 ostree: new package
eca8a1792 storage: add ostree files
58f557cf1 Merge pull request #191 from giuseppe/overlay-fuse-program
fc4b8629c containers-storage: add new option .fuse_program
51f1f85c2 Merge pull request #190 from marcov/better-failmsg
d990e2b32 Improve duplicate name error message on container create

### PR DESCRIPTION
**Pull request by runcom**
This check has been wrongly removed with #198 
The check must stay as it's now part of the Stop/Delete API so reintroduce it back
This fixes #233 and the associated CRI-O issues
This PR + https://github.com/kubernetes-sigs/cri-o/pull/1910 fully fix the issue

@rhatdan @nalind @sboeuf @chavafg PTAL 

I'm going to revendor c/storage in CRI-O to full fix crio after this is merged

Signed-off-by: Antonio Murdaca <runcom@linux.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I was attempting to look at Unmount to see if we should fail safely in there, but I think it gets a little complicated.  So this patch LGTM
@vrothberg @nalind @mtrmac PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM, definitely want other head nods on this.

I was worried that we could get stuck in the loop here, but the Unmount function looks like it will eventually error out or get the count below zero.

**Comment by vrothberg** [comment]
Code LGTM but I am picky with commit messages.

@runcom, could you add some description of why the change is necessary and add also link the other issues/PRs?

**Comment by runcom** [comment]
repushed with something in commit message

**Comment by vrothberg** [comment]
LGTM, thanks :) (I can't merge here)

> that's the commit title "layers: do not try to unmount if not mounted at all on delete", that's why it's necessary

I like the title as it really explains the change which is great for changelogs but I am currently on a crusade against commits without a message (see https://github.com/containers/common-files/blob/master/CONTRIBUTING.md#describe-your-changes-in-commit-messages). Github has turned most git histories into a very bad shape as most information is spread over PRs and issues.

**Comment by runcom** [comment]
> I like the title as it really explains the change which is great for changelogs but I am currently on a crusade against commits without a message (see https://github.com/containers/common-files/blob/master/CONTRIBUTING.md#describe-your-changes-in-commit-messages). Github has turned most git histories into a very bad shape as most information is spread over PRs and issues.

I concur with that yeah, kata-containers have a commit verifier which also makes sure that the body of a commit is _not_ empty and there's always an associated issue that a given commit is fixing so track is kept. Maybe one day we'll have something like that as well :)

**Comment by vrothberg** [comment]
@TomSweeneyRedHat and I were philosophizing about Github PR templates for all github.com/containers projects to link to https://github.com/containers/common-files/blob/master/CONTRIBUTING.md. But a but sounds really neat.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
