### PR TITLE
Remove "docker" strings from container storage

### PR DESCRIPTION
**Pull request by rhatdan**
We want to make sure that content created out of container storage
does not refer to docker.

### CODE REVIEW

**Comment by nalind** [comment]
@rhatdan Looks like a good start - can you also update what we pass to `ioutil.TempDir`, `reexec.Register` and `reexec.Command` under the `pkg` subdirectory?

**Comment by rhatdan** [comment]
I was not sure what those were doing.  Do they actually execute commands?

**Comment by nalind** [comment]
They're used for setting argv[0] when the calling process runs a second copy of itself as a subprocess, in this case so that it can be chrooted, to extract a layer onto disk.

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by nalind** [comment]
I think the `pkg/archive` and `pkg/chrootarchive` package still need a look, otherwise this looks complete.

**Comment by rhatdan** [comment]
I did not do any of the pkg packages since I thought they came from elsewhere.  I will take a quick look.

**Comment by nalind** [comment]
They're not vendored from elsewhere, so they "live" here as much as anything else.  They're isolated enough from the rest of the code that they could conceivably be spun off into their own repositories, but I expect that's more about maintainability than any actual intent to spin them off.

**Comment by rhatdan** [comment]
I modified the code that could be seen outside of test code.  I could change all of the references to the test code, if you want, but that would cause more hassle when trying to back port fixes.

**Comment by nalind** [comment]
Looks good, merging.

**Pull request merged**
