### PR TITLE
Start using github.com/moby/sys/mountinfo rather then local version

### PR DESCRIPTION
**Pull request by rhatdan**
This version of Mountinfo has been optimized for container use cases.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
After watching @kolyshkin Talk, I decided to look at what we are using for mountinfo.

@kolyshkin PTAL

**Comment by rhatdan** [comment]
I am attempting to not break API.

**Comment by kolyshkin** [comment]
The key for a seamless switch is to use type X=mountinfo.X and the same with functions.

For example, see https://github.com/moby/moby/pull/40694

**Comment by TomSweeneyRedHat** [comment]
All kinds of test ugliness @rhatdan

**Comment by kolyshkin** [comment]
Mocked up an alternative PR: https://github.com/containers/storage/pull/703

**Pull request closed without merging**
