### PR TITLE
Cirrus: Update VM Images

### PR DESCRIPTION
**Pull request by cevich**
Also adjust task-names for improved readability.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Re: testing w/ device mapper, there appear to be two persistent problems:

* The first test fails due to `level=error msg="File descriptor 3 (pipe:[60185]) leaked on pvdisplay invocation. Parent PID 29275: /var/tmp/go/src/github.com/cont\nFile descriptor 10 (/dev/mapper/control) leaked on pvdisplay invocation. Parent PID 29275: /var/tmp/go/src/github.com/cont\n  Failed to find physical volume \"/dev/sda2\".\n" error="exit status 5"`
* All tests then seem to fail due to a non-pristine state: `error initializing: /dev/sda2 is already part of a volume group "storage": must remove this device from any volume group or provide a different device`

Should I open two issues or one, or perhaps just remove this test (since it always fails and is ignored)?

**Comment by cevich** [comment]
okay, this is ready now apart from my question about 'devicemapper' testing (above).

**Comment by rhatdan** [comment]
Remove the test.

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
> Remove the test.

Oookay, those are the magic words...

**Pull request merged**
