### PR TITLE
Cirrus-CI: Give success a name

### PR DESCRIPTION
**Pull request by cevich**
This and the referenced openshift/release PR will make prow (via the tide bot) block merges unless the success aggregation task is green. This must be configured independently from branch-protection rules which tide does/can not manage due to write-only access.

### CODE REVIEW

**Comment by cevich** [comment]
***Note to me:*** Once this merges, the branch-protection rule for `main` needs to be updated to use the new name (matching tide).

**Review by saschagrunert — APPROVED** [review]

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by cevich** [comment]
(github branch-protection settings have been updated)

**Pull request merged**
