### PR TITLE
devmapper: allow devmapper devices as directlvm device

### PR DESCRIPTION
**Pull request by mikemccracken**
LVM allows creating a PV on top of an LV, but resolving symlinks
before checking the output of lvmdiskscan erroneously reports that an
LV is not an available device. It will resolve an LV's name into
/dev/dm-NN, which won't show up in lvmdiskscan.

Instead this patch looks for both names in lvmdiskscan.

The motivation for this was to allow using an LV instead of a whole PV as the backing device for the devicemapper driver.

### CODE REVIEW

**Comment by rhatdan** [comment]
@rhvgoyal PTAL

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@nalind @rhvgoyal @vrothberg @saschagrunert PTAL

**Comment by mikemccracken** [comment]
great, thanks all!

**Pull request merged**
