### PR TITLE
Move minimal golang to v1.20

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by mtrmac** [comment]
@rhatdan Please document the reason — is it “just” to be fresh, or is there something that doesn’t build with 1.19 now?

**Comment by mtrmac** [comment]
(The change LGTM, it’s just that I think it’s _so much_ easier to document the rationale now than to retroactively figure it out later, if the latter is even possible to do with certainty, that writing that down now is well worth it.)

**Comment by rhatdan** [comment]
The entire tool chain is moving to 1.20, so I see no reason to leave this behind.  1.19 support gos away soon, I believe if it is not already gone.

**Comment by mtrmac** [comment]
/lgtm

Fair enough.

**Pull request merged**
