### PR TITLE
store: use system.EnsureRemoveAll to rm container

### PR DESCRIPTION
**Pull request by giuseppe**
if the container deletion fails with the simple os.RemoveAll(path),
then attempt again using system.EnsureRemoveAll(path).

The difference is that system.EnsureRemoveAll(path) tries to umount
eventual mounts that are keeping the directory busy.

It might help with: https://github.com/containers/podman/issues/11594

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by umohnani8** [comment]
LGTM

**Comment by flouthoc** [comment]
LGTM , EnsureRemoveAll will do the replaced retries I guess.

**Review by flouthoc — APPROVED** [review]

**Comment by TomSweeneyRedHat** [comment]
LGTM
but it looks like a rebase is neeeded

**Comment by giuseppe** [comment]
rebased and pushed

**Comment by rhatdan** [comment]
Ignoring devicemapper flake.

**Pull request merged**
