### PR TITLE
quota: add build tag to disable it

### PR DESCRIPTION
**Pull request by giuseppe**
change backported from Moby.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by giuseppe** [comment]
the CI failure doesn't seem related to the PR

**Comment by giuseppe** [comment]
@nalind PTAL

**Comment by nalind** [comment]
Looks reasonable.  If we're not going to export the newly-added error for direct comparison (it would have to be moved to a place where it's unconditionally declared), then it might as well be allocated at the sites where it's being returned, so that a backtrace ends at the right place.  It's okay to merge in its current form, though.

**Comment by giuseppe** [comment]
> Looks reasonable. If we're not going to export the newly-added error for direct comparison (it would have to be moved to a place where it's unconditionally declared), then it might as well be allocated at the sites where it's being returned, so that a backtrace ends at the right place. It's okay to merge in its current form, though.

thanks, I've updated the PR and now the error is allocated where it is returned

**Comment by vrothberg** [comment]
Restarted the flaked job. Good to merge once we're green :-)

**Pull request merged**
