### PR TITLE
lockfile: make tests deterministic

### PR DESCRIPTION
**Pull request by vrothberg**
This is based on https://github.com/containers/storage/pull/310 and adds one commit on top to fix some test flakes.

### CODE REVIEW

**Comment by mtrmac** [comment]
Adding a `Sleep` to a test to make it more likely to pass makes me suspicious. It seems to me that either the tests are trying to hit a specific scenario (in which case the scenario should be set up deliberately and precisely, without hoping to be done in any particular time), or they are just stress-testing that the code does what the API promises and does not break invariants, in which case the tests should only be asserting what _must_ happen, not what _could_ happen.

---

I can’t reproduce this, what exactly is failing? The “read counter never have gone above 1 at least once” tests? I don’t quite see why we need hundreds of goroutines for that one—just create two that both lock the lock, report back success, and don’t unlock the lock in the goroutines until told to by the parent.

That’s more tricky in `TestLockfileMixedConcurrent`, where we do want to stress-test the lock; I’m tempted to just remove the check for >1 concurrent reader; the lock is not _required_ to allow any particular number of multiple readers at the same time, after all.

Or maybe engineer an exact situation, with a writer holding the lock, two readers blocked on trying to obtain it, and unlock the writer.

**Comment by vrothberg** [comment]
I think we can do both, some stress testing and another one to check for invariants. The latter is probably best done with channels or sth similar instead of sleeps. I did not have much time for a proper fix (while sleeps seem still more robust than the current state). I'll give it another try.

**Comment by vrothberg** [comment]
@nalind @rhatdan PTAL.

**Comment by rhatdan** [comment]
LGTM
@nalin can you merge this?

**Comment by TomSweeneyRedHat** [comment]
LGTM, but would like a @nalind head nod.

**Comment by nalind** [comment]
Looks reasonable.  Merging.

**Pull request merged**
