### PR TITLE
lockfile: fix a deadlock

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
This commit can be cherry-picked by @nalind for https://github.com/containers/storage/pull/289. I just realized the deadlock and figured to fix it while the east coast is asleep :)

**Comment by rhatdan** [comment]
LGTM
@nalind PTAL

**Comment by nalind** [comment]
If I'm reading this right, when two threads try to acquire locks, one for reading, the other for writing, they can both succeed.

**Comment by vrothberg** [comment]
> If I'm reading this right, when two threads try to acquire locks, one for reading, the other for writing, they can both succeed.

Ew, you are right. We've been shielded from that case before. I'll add a commit on top. Thanks, @nalind !

**Comment by vrothberg** [comment]
I was also actually wrong in the assumption that `fcntl` would block on in this case...

**Comment by vrothberg** [comment]
@nalind can you have another look at the latest commit? We're using a `sync.RWMutex` now which makes the code much simpler.

**Comment by nalind** [comment]
Yeah, that's in line with what I was thinking.  The tip of the version of #289 that's currently being chewed on by CI is similar enough that I'll see if it turns up anything before cherry-picking this and rebasing the tip on it.

**Comment by nalind** [comment]
LGTM

**Comment by vrothberg** [comment]
Thanks, @nalind! Closing as it has been cherry-picked in https://github.com/containers/storage/pull/289.

**Pull request closed without merging**
