### PR TITLE
 [release-1.45] Backport ignore chown errors in additionalimagestore

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Backports parts of https://github.com/containers/storage/pull/1828 and also https://github.com/containers/storage/pull/1784 to address:
https://issues.redhat.com/browse/ACCELFIX-244

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Lint is failing here trying to get to to Debian:

```
Err:5 http://deb.debian.org/debian stretch-backports Release
  404  Not Found [IP: 199.232.98.132 80]
```
I thought at first that it was due to the changes I made to the lint install in tests/Makefile, but I reverted that and the same error.  @cevich or @lsm5 are you aware of issues in this arena?

**Comment by edsantiago** [comment]
[Looks hopeless](https://cirrus-ci.com/task/5648185354354688)
```
echo "deb http://deb.debian.org/debian stretch-backports main" > /etc/apt/sources.list.d/backports.list
apt-get update
Get:1 http://deb.debian.org/debian bullseye InRelease [116 kB]
Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
Ign:4 http://deb.debian.org/debian stretch-backports InRelease
Err:5 http://deb.debian.org/debian stretch-backports Release
  404  Not Found [IP: 199.232.98.132 80]
Get:6 http://deb.debian.org/debian bullseye/main amd64 Packages [8068 kB]
Get:7 http://deb.debian.org/debian-security bullseye-security/main amd64 Packages [278 kB]
Get:8 http://deb.debian.org/debian bullseye-updates/main amd64 Packages [18.8 kB]
Reading package lists...
E: The repository 'http://deb.debian.org/debian stretch-backports Release' does not have a Release file.
```
I would just disable lint. This code is too old.

**Comment by rhatdan** [comment]
Agree, disable lint.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
