### PR TITLE
fix goroutine leak with close tatLogger in a defer clause

### PR DESCRIPTION
**Pull request by zvier**
Relate to #705

Signed-off-by: Jeff Zvier <zvier20@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @saschagrunert @giuseppe @vrothberg PTAL

**Comment by rhatdan** [comment]
Thanks @zvier

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
