### PR TITLE
overlay: check selinux label support

### PR DESCRIPTION
**Pull request by giuseppe**
Linux 5.11 introduced overlay for unprivileged users but it fails when
a SELinux label is specified to the mount.

Add a check in overlay to fallback to fuse-overlayfs when the system
is using SELinux but overlay doesn't support it.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
Fedora-33 overlay tests are failing.  I'm not sure if that's expected or not.

**Comment by giuseppe** [comment]
> Fedora-33 overlay tests are failing. I'm not sure if that's expected or not.

was a flake

**Comment by rhatdan** [comment]
LGTM

**Review by rhatdan — APPROVED** [review]

**Comment by nalind** [comment]
LGTM

**Review by vrothberg — COMMENTED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Trying to write up a justification for the BZ and get tests setup.  Can someone cut/paste into a comment an example command and the error generated when this bug hits?  @rhatdan @giuseppe ?

**Comment by giuseppe** [comment]
> Trying to write up a justification for the BZ and get tests setup. Can someone cut/paste into a comment an example command and the error generated when this bug hits? @rhatdan @giuseppe ?

```
Linux 5.11 introduced unprivileged overlay mounts but it has an issue when used together with SELinux labels.  Check that overlay supports SELinux labels before using it for unprivileged users.
```

**Comment by TomSweeneyRedHat** [comment]
Perfect, tyvm @giuseppe !

**Pull request merged**
