### PR TITLE
[release-1.45] quota: unlink tmp file before creating it 

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
Before creating the tmp file, we unlink it first to avoid an EEXIST
error.

Cherry Pick of https://github.com/containers/storage/commit/befd1479dde1cf37a86ed8bec927413a6a7b7d1a
Needed for Podman v4.4.1 backport.

Fixes: https://issues.redhat.com/browse/RHEL-3163

Also bump the version in this branch to v1.45.6, then back to 1.45.7-dev

[NO NEW TESTS NEEDED]

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@vrothberg and @mtrmac PTAL

**Comment by TomSweeneyRedHat** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
The test failure is lint not being able to find something in a Debian repo?

**Comment by TomSweeneyRedHat** [comment]
@cevich any idea where the lint failure from Debian is coming from?

**Comment by mtrmac** [comment]
(Backport LGTM.)

---

I think the difference is https://github.com/containers/storage/commit/c0c43e4f6858ce5c1fcf51b7ba134f0b8a7986da on `main`. I didn’t look into whether doing that is appropriate for a release branch, or whether we need to something else to preserve an older environment.

**Comment by TomSweeneyRedHat** [comment]
Per @cevich the test failure is expected in this branch

**Comment by TomSweeneyRedHat** [comment]
WIP test on Podman "fails", but fails in a test for "fedora-37-aarch64 rootless host" like other PR's in that branch fail.  @rhatdan, or @nalind, are you comfortable using the merge hammer on this?

**Pull request merged**
