### PR TITLE
Cirrus: Use libpod cache-images

### PR DESCRIPTION
**Pull request by cevich**
Previously automation on this project used the low-level VM images
mostly as-is from google.  However, due to many items fixed by
https://github.com/containers/libpod/pull/3632 it makes more sense
to use the cache-images instead.

Non-deterministic behavior is a severe detriment to testing
reliability.  By using the libpod cache-images, this projects inherits
the libpod PR-based image-build workflow, a slew of pre-installed
packages, along with disabled default background services.

This should result in both faster and more reliable testing.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
Hmmm, dang, was hoping this would be an easy switchero :frowning_face:

My guess: We've installed lots of packages into these images, likely one/more is getting in the way of items CI in this project was setup to build from source.

Any other clues?  (I'm not proficient in reading the test failures here)

**Comment by vrothberg** [comment]
> rm: cannot remove '/tmp/tmp.qrl.vpbzc16rlcnw/ro-root/overlay/d25b8f55353206b375e84d2452bdeb89b13354d5a1e5c97ae06ca52f773fdb28/merged': Device or resource busy

@nalind @rhatdan ?

> [+0003s]     UBUNTU_CACHE_IMAGE_NAME=ubuntu-18-libpod-5479475851034624
[+0003s] Unknown/Unsupported distro. ubuntu and/or version 18 for setup.sh

This one looks like we need to rename or adjust the script?

**Comment by nalind** [comment]
> > rm: cannot remove '/tmp/tmp.qrl.vpbzc16rlcnw/ro-root/overlay/d25b8f55353206b375e84d2452bdeb89b13354d5a1e5c97ae06ca52f773fdb28/merged': Device or resource busy
> 
> @nalind @rhatdan ?

The previous line's attempt to mount the middle layer produced an error result, but the cleanup attempt is failing because another layer (likely the one mounted at line 23) is still mounted.

**Comment by cevich** [comment]
> This one looks like we need to rename or adjust the script?

Yes, we were using Ubuntu 19, I don't have that as a cache-image (yet) for libpod, so dropped to 18.

**Comment by cevich** [comment]
> The previous line's attempt to mount the middle layer produced an error result, but the cleanup attempt is failing because another layer (likely the one mounted at line 23) is still mounted.

So my fear is the problem is caused at a higher-level, since the new images have MANY more packages pre-installed.  It's easily possible there are multiple copies of "things" on the system, and being used incorrectly different contexts.

Hmmm.  I think we need more data.

**Comment by cevich** [comment]
I think we probably need to focus on "setup" instead of the actual test failure.

> multiple copies of "things" on the system

Looking...I wonder about the fuse/overlay stuff.  This is what goes into a Fedora image:
https://github.com/containers/libpod/blob/master/contrib/cirrus/packer/fedora_setup.sh

and this is an Ubuntu image:
https://github.com/containers/libpod/blob/master/contrib/cirrus/packer/ubuntu_setup.sh

**Comment by cevich** [comment]
note to me:  Looks like only ubuntu 18 needs some `$DEBS_REQUIRED` adjustments (or make 19 available).  The Fedora's packaging looks "okay" to me, still not sure why they're dying during test :confused:

**Comment by cevich** [comment]
rebased, removed fuse3 and btrfs from ubuntu.

**Comment by cevich** [comment]
rebased, added libfuse2

**Comment by cevich** [comment]
@nalind It looks to me like the Fedora's are in better shape than Ubuntu 18.  I'm not finding fuse 3 available (standard) there, and it seems this is a requirement for fuse-overlay?  Since we're borrowing cache-images from libpod's workflow, there is no Ubuntu 19 available yet.  Just to be clear, if that's a hard-requirement, implementing it there will slow down this PR.  There are a few third-party repos available though, so I may go check those for fuse3 first before giving up.

On the Fedora's front, any hints at what could be going wrong with test?

I was thinking it might be helpful if I had the setup script splat out a list of the currently installed packages and versions.  If that would be helpful, what packages would you like to see included in the list?

P.S. My unspoken goal with this PR is also positional - so I can bring in a secondary partition for additional use in test :smile:

**Comment by cevich** [comment]
Assuming we need Ubuntu 19 here, opened https://github.com/containers/libpod/pull/3754

**Comment by cevich** [comment]
waiting on some bleeding-edge VM images to build, then will update/rebase and try again here...

**Comment by cevich** [comment]
Package updates of note (from `fedora-cloud-base-30-1-2-1556821664`):
* glibc
* glibc-common
* coreutils
* dbus
* systemd
* kernel-core

**Comment by rhatdan** [comment]
@cevich What's happening with this?

**Comment by cevich** [comment]
@rhatdan blocked by: #419

**Comment by cevich** [comment]
(rebased, added missing 'automake' package)

**Comment by cevich** [comment]
Note to me: update with images from https://github.com/containers/libpod/pull/4028

**Comment by cevich** [comment]
rebased/force-pushed w/ latest libpod VM images

**Comment by cevich** [comment]
(rebased to include #439)

**Comment by cevich** [comment]
Hehe, okay then, well dang, that was easy.

**Comment by rhatdan** [comment]
LGTM
@nalind PTAL

**Comment by nalind** [comment]
LGTM

**Pull request merged**
