### PR TITLE
Always return deep copies of Layers, Images, and Containers

### PR DESCRIPTION
**Pull request by nalind**
Always copy slices and maps in Layer, Image, and Container structures before handing them back to callers so that, even if they modify them directly, they won't accidentally mess with our in-memory copies of those fields in the copies of the structures that we're using.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@mtrmac PTAL

**Comment by rhatdan** [comment]
@mheon @bbaude PTAL

**Comment by mheon** [comment]
LGTM

**Comment by baude** [comment]
lgtm with two comments:

* when doing performance analysis in libpod, we see that deepcopies are expensive.
* would it make any sense to not export them so they cannot be accidently used?

**Comment by mtrmac** [comment]
Makes sense to me, subject to the very limited extent I understand c/storage.

**Comment by nalind** [comment]
We're already doing shallow copies of these items when returning them to callers, and I'd rather avoid making API changes at this time.

**Comment by rhatdan** [comment]
Ok I am going to merge, and users will have to make sure they don't hit performance issues.

**Pull request merged**
