### PR TITLE
Assorted nits reported by revive linter

### PR DESCRIPTION
**Pull request by kolyshkin**
See individual commits for details.

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by nalind** [comment]
Should this be enabling the linter in `.golangci.yml`, too?

**Comment by kolyshkin** [comment]
> Should this be enabling the linter in `.golangci.yml`, too?

This linter is sort of too opinionated, and thus it's best to run it manually and only fix those warnings that make sense.

We can, of course, annotate all the warnings that we don't want to fix, and then enable the linter, but I'm not sure it makes sense.

**Pull request merged**
