### PR TITLE
Fix FreeBSD support

### PR DESCRIPTION
**Pull request by dfr**
This corrects some minor bit-rot in the zfs driver and adds a sample storage.conf

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

You have to sign all of your commits.
The devmapper failure is a known flake.

**Comment by rhatdan** [comment]
Thanks @dfr

**Comment by dfr** [comment]
I've signed the commits (I think) and updated my branch

**Comment by flouthoc** [comment]
@dfr I think your commits are not signed yet, could you please take a look at instructions here to sign your commits https://github.com/containers/storage/pull/1213/checks?check_run_id=6097211504 or

**Comment by dfr** [comment]
Second attempt at signing :)

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Review by flouthoc — APPROVED** [review]
LGTM

@containers/storage-maintainers PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
