### PR TITLE
Fix file permissions from 01130 to 0600

### PR DESCRIPTION
**Pull request by isimluk**

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@TomSweeneyRedHat @vrothberg @nalind PTAL

**Comment by vrothberg** [comment]
LGTM, but please provide some commit messages in future commits. My squirrel brain won't remember what I did last week and change explanations really help me out there.

**Comment by rhatdan** [comment]
Yes @isimluk Please update your commit message to point out that you are fixing the zfs file creation.

**Comment by TomSweeneyRedHat** [comment]
LGTM with a commit message.

**Comment by isimluk** [comment]
Ah, sorry guys. I have now become totally used to see useless commit messages, so perhaps I let my standards deteriorate as well.

Improved the message.

**Comment by nalind** [comment]
LGTM

**Pull request merged**
