### PR TITLE
Switch to golang 1.15

### PR DESCRIPTION
**Pull request by saschagrunert**
We now use the latest golang release images for the CI.

### CODE REVIEW

**Comment by rhatdan** [comment]
golang 1.15 is not released for Fedora 32 yet, is this going to be a problem?

**Comment by saschagrunert** [comment]
> golang 1.15 is not released for Fedora 32 yet, is this going to be a problem?

I don't think so, the module system should be backwards compatible.

**Comment by rhatdan** [comment]
Needs a rebase and having lint issues.

**Comment by saschagrunert** [comment]
Rebased to resolve the conflicts

**Comment by TomSweeneyRedHat** [comment]
LGTM
But honest @saschagrunert it's saying "This branch is out-of-date with the base branch"

**Pull request merged**
