### PR TITLE
chmod/chown: handle EINTR

### PR DESCRIPTION
**Pull request by haircommander**
release 1.20 cherry-pick of https://github.com/containers/storage/pull/757, which will go into cri-o 1.19 (which builds off of go 1.15, and is susceptible to this problem)

### CODE REVIEW

**Comment by rhatdan** [comment]
@haircommander Lint is not happy with this back port.

**Comment by haircommander** [comment]
side note- why is this branch using such an old go, as <1.13 is no longer supported per https://golang.org/doc/devel/release.html#policy

**Comment by rhatdan** [comment]
Because no one has opened a PR to change this.
LGTM

**Comment by kolyshkin** [comment]
Can we have a release (1.20.5 I guess) with this change?

**Comment by haircommander** [comment]
I'll tag one

**Pull request merged**
