### PR TITLE
Allow any env variable for graphroot, runroot, storagepath

### PR DESCRIPTION
**Pull request by ashley-cui**
Previously only restricted to home, uid, and user

as per https://github.com/containers/buildah/issues/2311#issuecomment-671076880

Signed-off-by: Ashley Cui <acui@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Your removing tests, but you added none back int?  Can you add some test in this?

**Comment by ashley-cui** [comment]
@rhatdan the test i removed was just to check if the path only included env vars $HOME, $UID, $USER. since we want to allow other env vars to be set, i removed the test. i'm not quite sure how to write a test for the function i changed, since it automatically looks at .config/containers/storage.conf to parse storage.conf, other than using the same trick getRootlessRuntimeDirIsolated() uses. if this is okay, i'll do the trick, if not, let me know how to test it

**Comment by rhatdan** [comment]
Yes do the trick.

**Comment by rhatdan** [comment]
@nalind @giuseppe @saschagrunert @vrothberg @TomSweeneyRedHat PTAL

**Pull request merged**
