### PR TITLE
[v1.36 Backport] race, storage: add independent AddNames and RemoveNames for images,layers and containers

### PR DESCRIPTION
**Pull request by flouthoc**
Backport of: https://github.com/containers/storage/pull/1153

Adds AddNames and RemoveNames so operations which are invoked in parallel
manner can use it without destroying names from storage.

For instance

We are deleting names which were already written in store.
This creates faulty behavior when builds are invoked in parallel manner, as
this removes names for other builds.

To fix this behavior we must append to already written names and
override if needed. But this should be optional and not break public API

Following patch will be used by parallel operations at podman or buildah end, directly or indirectly.

### CODE REVIEW

**Comment by flouthoc** [comment]
@containers/storage-maintainers @giuseppe @nalind @rhatdan PTAL. I'm not sure if failing ubuntu test are related to the change in this PR.

**Review by vrothberg — COMMENTED** [review]
Could add two more commits:
1) Bump the version for a new release
2) Bump back to a -dev version

**Comment by vrothberg** [comment]
Restarted the Ubuntu jobs.  If they continue failing, we may need to call @cevich's hotline.

**Comment by flouthoc** [comment]
@vrothberg Done, although i see `c/storage` is using convention of `+dev` instead of `-dev`,  so I kept it `+dev`.

**Comment by flouthoc** [comment]
@TomSweeneyRedHat FYI

**Comment by cevich** [comment]
FWIW: The pattern we follow in every other repo. running tests on VMs is (especially for Ubuntu):

* Never do a blanket package update at test runtime, removals are okay.
* Make sure any runtime package installs ([example](https://github.com/containers/buildah/blob/bc5080ccdd742f7e24535ba2fc3fbf2acd3ba6b9/contrib/cirrus/setup.sh#L31-L34)) happen from pre-downloaded cache ([example](https://github.com/containers/automation_images/blob/752b774bb3e29fb11e43890f07fd978d8d1eac1e/cache_images/ubuntu_packaging.sh#L157-L168))
* or simply add the necessary packages into the list ([example](https://github.com/containers/automation_images/blob/752b774bb3e29fb11e43890f07fd978d8d1eac1e/cache_images/ubuntu_packaging.sh#L50)) to be installed (assuming they don't cause any interference in any other CI)

Legacy Fedora VMs are slightly more forgiving since their package repositories tend to remain available for quite a long time.  But ultimately they will be archived, so much of the same advice applies.

**Comment by TomSweeneyRedHat** [comment]
I'm going to close this PR.  If we need to backport, which I doubt, we can resurrect if necessary.

**Comment by flouthoc** [comment]
@containers/storage-maintainers @TomSweeneyRedHat It seems we need this patch in `v3.4.2-rhel` again. Could we review this PR and cut a new release once this is merged. 

Backport is similar to this https://github.com/containers/storage/pull/1174 so once this is merged and a new version I think `v1.36.2` is released then `v1.36.2` can be used by other dependencies.

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
@flouthoc which BZ does this backport address?

**Comment by flouthoc** [comment]
@TomSweeneyRedHat This was supposed to go into `v3.4.2-rhel` but I'm not sure if that is under consideration anymore or not. So nothing as of now.

**Comment by TomSweeneyRedHat** [comment]
Just for historical searches, it's good to put the BZ number in the PR, preferably in the Description.  If there's not one that's OK, but would like to have one added if there is a particular BZ this is aimed at.

**Pull request merged**
