### PR TITLE
Add flate back in, codespell was too agressive

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@mtrmac PTAL

**Review by mtrmac — APPROVED** [review]

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by TomSweeneyRedHat** [comment]
We'll need to be sure to bump c/storage for Podman v4.0 final then.

**Comment by mtrmac** [comment]
For this? It’s just a comment, not user-visible in any way.

IMHO this can just live on the main branch, and I personally don’t care one bit whether it is officially released in an hour or in 10 years.

**Comment by rhatdan** [comment]
@TomSweeneyRedHat another PR got merged, though which will force us to bump storage and common into Buildah and Podman before final release.

**Pull request merged**
