### PR TITLE
Don't fail trying to read xattrs on platforms that don't support them

### PR DESCRIPTION
**Pull request by mtrmac**

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @vrothberg @giuseppe @TomSweeneyRedHat PTAL

**Comment by nalind** [comment]
LGTM.  `system.Lgetxattr()` and friends return `system.ErrNotSupportedPlatform` on non-Linux systems.

**Comment by TomSweeneyRedHat** [comment]
LGTM but the tests seem rather turbulent

**Comment by rhatdan** [comment]
Not related to the PR, I am trying to get the images fixed in a different PR>

**Pull request merged**
