### PR TITLE
Update to match latest code in moby

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind We can either merge this or just start using it directly from Moby,  WDYT?

**Comment by rhatdan** [comment]
No that was a bug, Hopefully tests will pass now.

**Comment by nalind** [comment]
Looks fine, but since we're not using the index's `Iterate()` method, can we list the motivation for the update in the commit log?

**Comment by rhatdan** [comment]
Merging.

**Pull request merged**
