### PR TITLE
support patches to prepare #775

### PR DESCRIPTION
**Pull request by giuseppe**
move some patches from #775 to a new PR to simplify the review process.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@saschagrunert @vrothberg @TomSweeneyRedHat @nalind PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
rebased

**Pull request merged**
