### PR TITLE
Rename 'overlay2' to 'overlay'

### PR DESCRIPTION
**Pull request by nalind**
Finish the overlay->overlay2 changeover by:
* renaming overlay2 to overlay
  * teaching the driver to accept the overlay.override_kernel_check and
    overlay2.override_kernel_check options as having the same meaning
* registering the driver init function using both names

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by nalind** [comment]
Added a bit of logic to have driver.String() return the name that was used to look up its init function.

**Comment by nalind** [comment]
I think this is where we're breaking https://github.com/kubernetes-incubator/cri-o/pull/450 ATM.

**Comment by rhatdan** [comment]
👍

**Pull request merged**
