### PR TITLE
chrootarchive: propagate env from parent

### PR DESCRIPTION
**Pull request by giuseppe**
propagate the environment variables from the current process since they are needed by pkg/unshare to read the UID for the user that created the user namespace (through the _CONTAINERS_ROOTLESS_UID env variable).

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by nalind** [comment]
This currently changes two of the places where we call `userns.RunningInUserNS()` without touching several others.  What's the rationale?

**Comment by giuseppe** [comment]
> This currently changes two of the places where we call `userns.RunningInUserNS()` without touching several others. What's the rationale?

I've touched only the file that I was working on as part of the fix.  I agree it makes no sense to change only that, so I've adapted other files as well and pushed a new version

**Comment by rhatdan** [comment]
LGTM

**Comment by Luap99** [comment]
I applied this fix in https://github.com/containers/podman/pull/15695 and it seems to work (at least the compose and API tests which failed previously are now green).

**Review by flouthoc — APPROVED** [review]
LGTM

**Pull request merged**
