### PR TITLE
Improve duplicate name error message on container create

### PR DESCRIPTION
**Pull request by marcov**
Make the error message more informative by specifying the duplicate name
and the existing container ID. Implements #189.

Opening this PR as asked by @rhatdan and agreed with @vrothberg

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by rhatdan** [comment]
@marcov I think you need to update the ffjson files.  If you run make does it recompile them?

**Comment by vrothberg** [comment]
LGTM (given the CI passes)

Note that this PR does not yet fully implement https://github.com/containers/storage/issues/189 as there are other error cases that could be improved in a similar fashion (see https://github.com/containers/storage/blob/master/errors.go). Such cases can be duplicate ID, or layer in use, etc. I suggest looking at the code using the errors and see what can be done (in follow-up PRs).

**Comment by nalind** [comment]
@marcov could you `go install github.com/pquerna/ffjson`, run `ffjson containers.go`, and add the updated `containers_ffjson.go` to the patch?  That should keep CI from trying to do the same at build-time.

**Comment by marcov** [comment]
@rhatdan, @nalind: I tried to run ```ffjson``` locally and it just regenerate exactly the same ```containers_ffjson.go```. 

The CI logs make this look more like an issue in the CI env:
```
rm -f containers_ffjson.go
ffjson containers.go
make: ffjson: Command not found
Makefile:33: recipe for target 'containers_ffjson.go' failed
make: *** [containers_ffjson.go] Error 127
```

**Comment by rhatdan** [comment]
I think the makefile wants to generate an updated version. If you run make locally does it execute the ffjson command?

**Comment by marcov** [comment]
OK did like you said.

**Comment by rhatdan** [comment]
Thanks  Lets see if it passes tests.

**Comment by rhatdan** [comment]
Woo Hoo, the hack worked.
@nalind PTAL

**Comment by nalind** [comment]
LGTM, merging.

**Pull request merged**
