### PR TITLE
Fix build on FreeBSD

### PR DESCRIPTION
**Pull request by mateuszkwiatkowski**
Fix for https://github.com/containers/storage/issues/297

Although that fixes the build on FreeBSD I'm not experienced with Go so please validate these changes.

Signed-off-by: Mateusz Kwiatkowski <mateusz@serveraptor.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@mateuszkwiatkowski Thanks for the submission.  It looks like you've some compilation errors to work through.

```
go build -compiler gc -tags " libdm_no_deferred_remove ostree "  ./cmd/containers-storage
# github.com/containers/storage
./lockfile_unix.go:209:20: (*lockfile).TouchedSince redeclared in this block
	previous declaration at ./lockfile_linux.go:12:6
./lockfile_unix.go:215:22: not enough arguments in call to time.Unix
./lockfile_unix.go:215:25: st.Mtimespec undefined (type unix.Stat_t has no field or method Mtimespec)
Makefile:22: recipe for target 'containers-storage' failed
make: *** [containers-storage] Error 2
```

**Comment by mateuszkwiatkowski** [comment]
@TomSweeneyRedHat thanks for headsup. So it seems that file `lockfile_darwin.go` isn't compiled on FreeBSD and this is the root cause of the error:
```
$ go list -f '{{.GoFiles}}'
[containers.go containers_ffjson.go errors.go images.go images_ffjson.go layers.go layers_ffjson.go lockfile.go lockfile_unix.go store.go]
```
 I reverted changes I made in `lockfile_unix.go` and simply copied `lockfile_darwin.go` to `lockfile_freebsd.go`. Now, the file is on the list:

```
% go list -f '{{.GoFiles}}'
[containers.go containers_ffjson.go errors.go images.go images_ffjson.go layers.go layers_ffjson.go lockfile.go lockfile_freebsd.go lockfile_unix.go store.go]
```

I don't know how to achieve the goal without duplicating the code so I'll appreciate any tips if you think that it's a problem.

**Comment by rhatdan** [comment]
Will it work if you make it a symbolic link?

**Comment by rhatdan** [comment]
Of if you renamed it to podman_otherunix.go

**Comment by mateuszkwiatkowski** [comment]
@rhatdan seems that renaming `lockfile_darwin.go` to `lockfile_otherunix.go` does the trick:
```
$ go list -f '{{.GoFiles}}'
[containers.go containers_ffjson.go errors.go images.go images_ffjson.go layers.go layers_ffjson.go lockfile.go lockfile_otherunix.go lockfile_unix.go store.go]
```

I'm not able to test it on Darwin or Linux though.

**Comment by rhatdan** [comment]
Should not affect Linux and I am 99.9% sure it will not effect Darwin, All we are doing right now and is making sure it compiles on Macs/

**Comment by giuseppe** [comment]
I've restarted the Fedora task on Travis as it seemed a flake

**Comment by rhatdan** [comment]
@mateuszkwiatkowski Can you just switch the PR to the rename.

**Comment by rhatdan** [comment]
Closing for #302

**Pull request closed without merging**
