### PR TITLE
[1.24] Backport: ignore metacopy option on kernels that do not support it

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by rhatdan** [comment]
@saschagrunert @vrothberg @mheon @giuseppe @nalind @umohnani8 @TomSweeneyRedHat PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
The ubuntu failures have nothing to do with this PR.  Merging.

**Pull request merged**
