### PR TITLE
Cirrus: Support additional test-storage

### PR DESCRIPTION
**Pull request by cevich**
***Note: Depends on #408***

### CODE REVIEW

**Comment by cevich** [comment]
note to me: Add matrix-axis over overlay vs devicemapper for `build_and_test.sh`

**Comment by rhatdan** [comment]
@cevich What's happening with this?

**Comment by cevich** [comment]
@rhatdan also blocked by: #419

**Comment by rhatdan** [comment]
@cevich Still interested in this? Needs a rebase,  Seems the PR that this was blocked on, has been merged.

**Comment by cevich** [comment]
@rhatdan this was to support testing w/ device-mapper IIRC, somethong **YOU** asked...are **YOU** still interested?  hehehehe :smile:

Closing this is an option...in case it's no-longer a priority.  I'm completely fine either way.

I'm steaming forward w/ updating libpod to use F30/F31, then will need to do that for all the other containers repo automation setups including this one.  If this capability is still wanted/needed, I think it might make more sense to return here once the update effort's complete.

**Comment by rhatdan** [comment]
Ah yes, then I guess I still do want this.

**Comment by cevich** [comment]
> Ah yes, then I guess I still do want this.

I figured so.  Most of the work actually already went into libpod, this and #408 just enable it + improve overall CI performance.

**Comment by cevich** [comment]
Oh! Well huh, okay!  That was much easier than I anticipated.

**Comment by cevich** [comment]
@rhatdan working now and F31 support to boot :smile: Feel free to tinker with the size/setup as needed

```
...from contrib/cirrus/setup.sh...
[+0110s] --------------------------------------------------
[+0110s] +  pvcreate /dev/sda2
[+0110s]   Physical volume "/dev/sda2" successfully created.
[+0110s] --------------------------------------------------
[+0110s] +  vgcreate test_vg /dev/sda2
[+0110s]   Volume group "test_vg" successfully created
[+0110s] --------------------------------------------------
[+0110s] +  lvcreate -l 33%FREE --name test_lv test_vg
[+0110s]   Logical volume "test_lv" created.
[+0110s] Test device /dev/test_vg/test_lv is ready to go
```

Note this is **only** supported in Fedora - re-partitioning Ubuntu's cloud-images is unnaturally difficult with standard tooling.

**Comment by rhatdan** [comment]
Which forces us to still rely on travis for Ubuntu testing.

**Comment by cevich** [comment]
oh?  I didn't see we were testing devicemapper in travis, only VFS, no?  /me goes to look again...

**Comment by cevich** [comment]
...ya, from the driver test, it seems like "vfs" is the default when STORAGE_DRIVER="" and no LVM tooling is present (which I'm assuming is the case).

For reference: it's not impossible to do custom storage in Ubuntu VMs, just needs lots of work.  The readily available cloud images have a super-funky partitioning scheme that breaks all attempts to modify it using standard tools (EFI and Boot partition numbers are 14 & 15 but root is 1 :S

**Comment by rhatdan** [comment]
I am fine with only doing the tests on Fedora,Centos and/or RHEL

**Comment by cevich** [comment]
@rhatdan PTAL these two devicemapper test failures.  I believe they both show an identical bug in the devicemapper tests:

1. [Fedora 30 +  `make STORAGE_DRIVER=devicemapper STORAGE_OPTION=dm.directlvm_device=/dev/sda2 local-test-integration` output](https://cirrus-ci.com/task/5238061118259200?command=build_and_test#L56)
2. [Fedora 31 +`make STORAGE_DRIVER=devicemapper STORAGE_OPTION=dm.directlvm_device=/dev/sda2 local-test-integration` output](https://cirrus-ci.com/task/4604742420660224?command=build_and_test#L56)

I'm happy to wait for / help test a fix, or if we want to move this PR forward independently, I can temporarily make just the devicemapper tests "optional".  Let me know what you prefer.

**Comment by cevich** [comment]
Update: @rhatdan I made it so cirrus/github ignores result of devicemapper testing due to bug.  Reverting the commit `￼Cirrus: Temp. Tolerate devicemapper test failure` will make them required (once bug(s) are fixed).

**Comment by rhatdan** [comment]
@nalind @vrothberg @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM but would prefer another head nod.

**Comment by cevich** [comment]
> would prefer another head nod.

Yep np, I'm just pusing buttons, have no real idea what they do :grin:

**Comment by nalind** [comment]
We stopped running unit tests here.

**Pull request merged**
