### PR TITLE
fileutils: make (Le|E)xists return os.PathError

### PR DESCRIPTION
**Pull request by giuseppe**
wrap the returned error in a os.PathError so the error includes the file path.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Review by Luap99 — COMMENTED** [review]
LGTM

**Comment by giuseppe** [comment]
@Luap99 @rhatdan anyone wants to drop a /lgtm? :)

**Comment by Luap99** [comment]
> @Luap99 @rhatdan anyone wants to drop a /lgtm? :)

I don't consider myself a storage maintainer so I am reluctant to merge anything here. Anyhow this change seem trivial enough so I guess I can make a exception.

/lgtm

**Pull request merged**
