### PR TITLE
(*store).Diff: add missing unlock in error case

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

@nalind @giuseppe PTAL

### CODE REVIEW

**Comment by nalind** [comment]
LGTM.  Nice catch!

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
Needs a rebase

**Comment by vrothberg** [comment]
> Needs a rebase

done

**Pull request merged**
