### PR TITLE
Follow symlinks if they exists

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/10187

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe PTAL

https://github.com/containers/podman/issues/10187#issuecomment-853958276
This is a followup on ^^

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@saschagrunert @nalind @TomSweeneyRedHat @vrothberg @ashley-cui  @umohnani8 PTAL

**Review by saschagrunert — APPROVED** [review]
LGTM

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
