### PR TITLE
layerStore.Diff(): don't add an unnecessary buffer

### PR DESCRIPTION
**Pull request by nalind**
Don't `ReadAll()` from a `Reader` to create a buffer and then create another `Reader` to read from that buffer.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, if this works.  Is this something we should test against buildah before we merge?

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM, tests do not.  A test with Buildah would be good.

**Comment by nalind** [comment]
We were potentially closing the underlying file and the pgzip decompression filter before the JSON decoder had finished reading from the decompression filter, and that appears to have created a hang when we stopped buffering up all of the file's contents at the first step.  The JSON decoder and pgzip decompressor are both advertised as potentially reading more information than they strictly require if there's some available, so I'm guessing that a partial read left one or the other was waiting for more information that would never come.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
