### PR TITLE
store: support volatile containers

### PR DESCRIPTION
**Pull request by giuseppe**
add a new class of containers that are not guaranteed to survive a crash.  The advantage of such containers is that storage can be
optimized to skip some synchronizations with the underlying storage.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@nalind @rhatdan how can we expose this setting to Podman/Buildah?  Should we enable it by default with Buildah containers?

**Comment by rhatdan** [comment]
I think enabling this by default for buildah makes sense.  

What is the use case for this on Podman?  `podman run --rm` ?

I think we need to have the fix for cleaning up bad containers easily though.

**Comment by rhatdan** [comment]
podman mount could probably use this flag as well.

**Comment by giuseppe** [comment]
The patch for Buildah is trivial:

```
diff --git a/new.go b/new.go
index 2ee86dd1..b95e680a 100644
--- a/new.go
+++ b/new.go
@@ -359,6 +359,7 @@ func newBuilder(ctx context.Context, store storage.Store, options BuilderOptions
                coptions := storage.ContainerOptions{
                        LabelOpts:        options.CommonBuildOpts.LabelOpts,
                        IDMappingOptions: newContainerIDMappingOptions(options.IDMappingOptions),
+                       Volatile:         true,
                }
                container, err = store.CreateContainer("", []string{tmpName}, imageID, "", "", &coptions)
                if err == nil {
```

I think this option must be enabled by default for Buildah and CRI-O (do we even want a way to disable it?).

For Podman instead it must be an explicit setting except when `--rm` is used: `podman run --volatile`?

**Comment by rhatdan** [comment]
Have you thought about how we clean this up, if we get corrupt containers?  Can we easily remove them?

**Comment by giuseppe** [comment]
> Have you thought about how we clean this up, if we get corrupt containers? Can we easily remove them?

containers can be removed in the usual fashion (e.g. podman rm).  Or do you think they should be removed automatically on shutdown?

I'd leave users the choice on such containers, for example it is safe to run volatile containers, stop them and run manually (sync/syncfs).

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
But will the tools be smart enough to discover bad containers?

**Comment by rhatdan** [comment]
@saschagrunert @vrothberg @nalind @TomSweeneyRedHat PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM, I leave merging up to you in case you want to continue talking about the UX in the tools

**Comment by rhatdan** [comment]
@giuseppe rebase and we can merge.

**Comment by giuseppe** [comment]
I am changing idea about "volatile" and start to think it should be a mount opt, so it can be more easily used with `--storage-opt`

**Comment by giuseppe** [comment]
rebased

**Comment by cgwalters** [comment]
Did anything else happen with this?  ISTM that e.g. `podman run --rm` for example should use this by default, because the processes and filesystem are defined to be lifecycled together.  

For Kubernetes where that's the default, crio should just start doing this everywhere right?

**Comment by giuseppe** [comment]
Both Podman, Buildah and CRI-O are taking advantage of it on kernels where volatile is supported.  CRI-O is doing it for every container, while Podman only when `--rm` is used

**Comment by nalind** [comment]
How are you checking for it?

**Comment by cgwalters** [comment]
> How are you checking for it?

```
[core@cosa-devsh ~]$ rpm-ostree status
State: idle
Deployments:
● fedora:fedora/x86_64/coreos/testing-devel
                   Version: 36.20220602.dev.0 (2022-06-02T15:24:13Z)
                    Commit: 12d5c0e6c587826e2e78ae6b72981f4d3f7609755883f994701d486831d75d83
              GPGSignature: (unsigned)
[core@cosa-devsh ~]$ rpm -q podman
podman-4.1.0-1.fc36.x86_64
[core@cosa-devsh ~]$ podman run --rm -ti busybox sleep 1h&
[core@cosa-devsh ~]$ podman unshare
Failed to connect to bus: Operation not permitted
[root@cosa-devsh ~]# findmnt |grep overlay
│ └─/var/home/core/.local/share/containers/storage/overlay /dev/vda4[/ostree/deploy/fedora-coreos/var/home/core/.local/share/containers/storage/overlay]                         xfs        rw,relatime,seclabel,attr2,inode64,logbufs=8,logbsize=32k,prjquota
```

I'd expect to see `volatile` in there.  I don't see the `incompat/volatile` in the storage directories.

OK, I see this bit https://github.com/containers/podman/blob/13cdf862e6dbf31902405e4204a5bd87f62a9759/pkg/specgenutil/specgen.go#L832 which seems like it should be setting it...

**Comment by nalind** [comment]
(The overlay directory itself is being bind mounted with different propagation options.)

**Comment by cgwalters** [comment]
> That's an xfs mount, not overlay. 

Right sorry.

> Try "podman run --rm fedora-minimal findmnt /".
> (The overlay directory itself is being bind mounted with different propagation options.)

Hum...interesting.  OK you're right, I do see `volatile` there.  Thanks.

**Pull request merged**
