### PR TITLE
remove useless code

### PR DESCRIPTION
**Pull request by weekface**

### CODE REVIEW

**Comment by weekface** [comment]
CI failed with:
```
make[1]: Leaving directory `/home/travis/gopath/src/github.com/containers/storage'
make[1]: Entering directory `/home/travis/gopath/src/github.com/containers/storage'
make[1]: Nothing to be done for `local-binary'.
make[1]: Leaving directory `/home/travis/gopath/src/github.com/containers/storage'
 6bdd0d5 - FAIL - does not have a valid DCO
1 commits to fix
make: *** [local-validate] Error 1
The command "make local-binary docs local-cross local-validate" exited with 2.
```
What is wrong?

**Comment by rhatdan** [comment]
You have to sign your PR.
git commit -a --amend -s
git push --force 

Should fix the issue.

**Comment by rhatdan** [comment]
That is a weird piece of code, but removing it seems correct.  @nalind any idea where this code came from?

**Comment by nalind** [comment]
It's a leftover from early days, when the "layer" subdirectory under "storage" was renamed to include the name of the driver, to avoid the possibility that we'd try to run one driver with the list of layers, images, and containers that actually corresponded to those that were being managed by another driver.
Anyway, LGTM.

**Comment by rhatdan** [comment]
@weekface Thanks for the patch.
LGTM

**Pull request merged**
