### PR TITLE
loopback: always return error if no loopback device

### PR DESCRIPTION
**Pull request by giuseppe**
simplify the error handling for openNextAvailableLoopback and avoid named return values

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@mtrmac @nalind @saschagrunert PTAL

**Review by mtrmac — COMMENTED** [review]
LGTM, I have learned to strongly distrust named return values and I like this.

Absolutely non-blocking: consider turning the top-level loop into a canonical `for remaining := …; remaining > 0; remaining--` instead of a notionally-infinite one.

**Review by saschagrunert — APPROVED** [review]

**Pull request merged**
