### PR TITLE
Add make vendor-in-container

### PR DESCRIPTION
**Pull request by rhatdan**
In order to always run vendor with the latest supported version of golang,
add the ability to run the vendor command within a podman container.

After running the command include vendor changes.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@vrothberg PTAL

**Comment by rhatdan** [comment]
@nalind @giuseppe @vrothberg @TomSweeneyRedHat PTAL

**Comment by nalind** [comment]
LGTM, but the commit log calls it "validate-in-container", not "vendor-in-container", so please correct that.

**Comment by rhatdan** [comment]
Oops fixed.

**Comment by rhatdan** [comment]
Previously we were running with golang 1.12, now we are running with golang 1.13, so these changes are caused by the new golang compiler.

We want everyone using 1.13, buf if you are running on an older OS, you can use 
make vendor-in-container to use it if your golang < 1.13

**Comment by TomSweeneyRedHat** [comment]
@rhatdan, so you did `make` in your sandbox and golang vendored these in then you did  git add/commit/push, etc?

**Comment by rhatdan** [comment]
Correct.

**Pull request merged**
