### PR TITLE
Switch to golangci-lint

### PR DESCRIPTION
**Pull request by saschagrunert**
This commit uses internal tools vendoring to switch to golangci-lint. All
working linters have been enabled. The other tools have been vendored as
well into the same tools folder, whereas the corresponding test and
build targets have been adapted as well.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Okay, this should be fine now. :innocent: PTAL

**Comment by rhatdan** [comment]
LGTM
@nalind PTAL

**Comment by rhatdan** [comment]
@saschagrunert Ubuntu Failure?

**Comment by saschagrunert** [comment]
> @saschagrunert Ubuntu Failure?

Yeah, I made the `lint` step a dedicated task in cirrus, which should work now.

**Comment by rhatdan** [comment]
@vrothberg @giuseppe @TomSweeneyRedHat PTAL

**Pull request merged**
