### PR TITLE
Replace deprecated repo 'github.com/docker/engine-api'

### PR DESCRIPTION
**Pull request by louyihua**
Since this repo is marked deprecated, we should import types from 'github.com/docker/docker/api' instead.

### CODE REVIEW

**Comment by rhatdan** [comment]
@louyihua Please sign your PR.

**Comment by louyihua** [comment]
@rhatdan OK, signed for now.

**Comment by rhatdan** [comment]
LGTM
@nalind PTAL

**Comment by nalind** [comment]
LGTM

**Pull request merged**
