### PR TITLE
Update deps to github.com/sirupsen/logrus v1.0.0

### PR DESCRIPTION
**Pull request by mrunalp**
Also updates github.com/Microsoft/hcsshim
and github.com/docker/go-connections so they work
with the newer version of logrus.

Signed-off-by: Mrunal Patel <mrunalp@gmail.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by runcom** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by nalind** [comment]
Please update the commit log message to mention the other deps this is explicitly bumping.  Otherwise, LGTM.

**Comment by mrunalp** [comment]
@nalind Updated.

**Comment by nalind** [comment]
LGTM, merging.

**Pull request merged**
