### PR TITLE
WIP - store.DeleteImage: only delete layer if it exists

### PR DESCRIPTION
**Pull request by vrothberg**
Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Fixes #371

**Comment by saschagrunert** [comment]
Thanks for taking care of the issue :pray:

**Comment by vrothberg** [comment]
Thanks! I am still not 100 percent sure **how** this could happen, since the code in questions is locked (see https://github.com/containers/storage/blob/master/store.go#L2149), which excludes both, threads and processes.

**Comment by vrothberg** [comment]
Don't merge. @saschagrunert and I are debugging atm.

**Comment by vrothberg** [comment]
Closing as the deletion is a red herring, seehttps://github.com/containers/storage/issues/371#issuecomment-505010750.

**Comment by mtrmac** [comment]
Guessing the link should be https://github.com/containers/storage/issues/371#issuecomment-505010750 .

**Pull request closed without merging**
