### PR TITLE
idmap: new package

### PR DESCRIPTION
**Pull request by giuseppe**
move the idmap utils from the overlay driver to a separate package.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@nalind @vrothberg @saschagrunert @flouthoc @umohnani8 @mtrmac PTAL

**Review by mtrmac — COMMENTED** [review]
Nothing here says why this is being done. So, why? (This is not a “no”, this is “in 5 years someone might well be asking what we were thinking today”.)

---

Does this need to be a public stable API of c/storage, or would `internal/idmap` do?

**Comment by giuseppe** [comment]
I'd like to use it from Podman, so it needs to be a public API.  My WIP on Podman is currently here: https://github.com/giuseppe/libpod/tree/idmap-rootfs

**Comment by mtrmac** [comment]
Thanks for the explanation. LGTM.

**Pull request merged**
