### PR TITLE
Switch to go modules

### PR DESCRIPTION
**Pull request by saschagrunert**
Remove the old vendor approach in replacement of go module support. Outdated dependencies have been updated as well. Except docker, where the API changed.

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by nalind** [comment]
This looks like it pulls in an older `runc` than we were using previously.  Not that the version we had been vendoring was recent, either, but still.  Otherwise LGTM.

**Comment by rhatdan** [comment]
Lets vendor in the latest runc available.

**Comment by saschagrunert** [comment]
> Lets vendor in the latest runc available.

Yes, I vendored in runc 1.0.0-rc8. This was mainly caused because go is not able to "detect" it as latest version correctly.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
