### PR TITLE
canUseShifting can segfault

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/podman/issues/10535

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @edsantiago PTAL

**Comment by edsantiago** [comment]
LGTM, in principle, but do you have any idea what could've led to `s.graphDriver` being uninitialized in this particular instance?

**Comment by rhatdan** [comment]
No idea, @giuseppe needs to look at this, This change just makes it safer.

**Comment by giuseppe** [comment]
what do you think if we just move the check later in `mount()` where we are sure `s.graph` is not nil?

```
diff --git a/store.go b/store.go
index 759407c63..8331fafde 100644
--- a/store.go
+++ b/store.go
@@ -2666,6 +2666,10 @@ func (s *store) mount(id string, options drivers.MountOpts) (string, error) {
                s.lastLoaded = time.Now()
        }
 
+       if options.UidMaps != nil || options.GidMaps != nil {
+               options.DisableShifting = !s.canUseShifting(options.UidMaps, options.GidMaps)
+       }
+
        if rlstore.Exists(id) {
                return rlstore.Mount(id, options)
        }
@@ -2706,7 +2710,6 @@ func (s *store) Mount(id, mountLabel string) (string, error) {
                                options.Volatile = v.(bool)
                        }
                }
-               options.DisableShifting = !s.canUseShifting(container.UIDMap, container.GIDMap)
        }
        return s.mount(id, options)
 }
```

Otherwise we may end up using shifting even if the driver doesn't support it

**Comment by rhatdan** [comment]
@giuseppe Looking at this, I am not sure this should be handled at the store level at all.  I think we should just remove this and do it at the driver level. Is it your intention to allow users in their storage.conf to specify to disable shifting?

**Comment by giuseppe** [comment]
> @giuseppe Looking at this, I am not sure this should be handled at the store level at all. I think we should just remove this and do it at the driver level. Is it your intention to allow users in their storage.conf to specify to disable shifting?

I think the store needs to know when shifting is supported by the underlying driver.  When it is not supported it needs to create a copy of the image with the shifted IDs.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@saschagrunert @vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
