### PR TITLE
Two misc. cleanups

### PR DESCRIPTION
**Pull request by mtrmac**
… just to reduce the size of my branches a bit.

See individual commit messages for details. I’d be happy to split this into two PRs if desired.

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@cevich PTAL

**Comment by cevich** [comment]
I don't know how that bot works, @baude is the SME.  Unless there are some docs somewhere on it?

**Pull request merged**
