### PR TITLE
Bump to v1.49.0 

### PR DESCRIPTION
**Pull request by rhatdan**

### CODE REVIEW

**Comment by vrothberg** [comment]
Can elaborate on why we need a new minor release?

**Comment by vrothberg** [comment]
... and why you force merged it without review?

**Comment by rhatdan** [comment]
There only integers we have plenty to go around. Previous update is causing Vendoring to go haywire.  This update will fix that and prevent future updates of older versions from hitting other repos incorrectly.

**Comment by vrothberg** [comment]
So we do releases now to work around vendor bots and all that without reviews?  I am really no fan :(

**Comment by rhatdan** [comment]
We did not release for two months and builtup  a lot of fixes, and bumping takes 10 seconds and affects very little to work around bots issues.

**Comment by vrothberg** [comment]
We just did a patch release (1.48.1) today.  1.49.0 will not be used anywhere and is missing patches (https://github.com/containers/storage/pull/1691).  I assume the sole purpose was to silence the vendor bots but I hope there's a better solution than cutting ghost releases.

**Comment by mtrmac** [comment]
> I assume the sole purpose was to silence the vendor bots but I hope there's a better solution than cutting ghost releases.

Merge the release branch into the main one, as c/image is now regularly doing.

That would also surface the code missing on the main branch, and bring it there.

**Pull request merged**
