### PR TITLE
[1.48.0] fix BZ 2232308 and bump version

### PR DESCRIPTION
**Pull request by vrothberg**

### CODE REVIEW

**Comment by vrothberg** [comment]
@TomSweeneyRedHat @giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
I'm late, but LGTM.  Thanks!

**Comment by nalind** [comment]
This change to `DiffSize()` is different from what did #1688 did to `main`.  Which one is correct?

**Comment by vrothberg** [comment]
Both are. For main there is another PR https://github.com/containers/storage/pull/1691 but CI is farting.

**Pull request merged**
