### PR TITLE
test helper: maxArgs = 0 is actually a meaningful value

### PR DESCRIPTION
**Pull request by nalind**
We do have commands that don't take any arguments, and quietly ignoring arguments when they get them is not a good idea.

### CODE REVIEW

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by nalind** [comment]
Rebased.

**Comment by rhatdan** [comment]
@giuseppe @cevich @saschagrunert @flouthoc @umohnani8 @vrothberg PTAL

**Comment by umohnani8** [comment]
LGTM

**Pull request merged**
