### PR TITLE
LVM Driver with SELinux context

### PR DESCRIPTION
**Pull request by haircommander**
In testing @nalind's LVM driver, I found there was an SELinux denial because the LVM mount was unlabeled and thus couldn't be exec'd on. Fix this by adding SELinux context to the mount. This allows Podman to use the LVM driver with just a change to /etc/containers/storage.conf

### CODE REVIEW

**Comment by haircommander** [comment]
@rhatdan @nalind PTAL, I finally found how to do this!

**Comment by haircommander** [comment]
@nalind @rhatdan FINALLY got CI tests working locally. I don't love my solution, however. We weren't passing because /dev wasn't a volume mounted on the host in the container that ran the tests, so the lvm commands just kept crashing and being confused. 

Is the addition of the volume mount for /dev in CI problematic in the long run?

**Comment by haircommander** [comment]
(okay giving the containers even more capabilities and I'm fairly certain it's too much but I'm just testing so definitely WIP DO NOT MERGE)

**Comment by rhatdan** [comment]
Could you try with just /dev/mapper volume mounted into the container, perhaps this will fix the aufs problems?

**Comment by rhatdan** [comment]
Since no one has worked on this in a couple of years, I see no reason to keep this open.
Closing.

**Pull request closed without merging**
