### PR TITLE
overlay: do not attempt metacopyup when using a mount program

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <giuseppe@scrivano.org>

### CODE REVIEW

**Comment by rhatdan** [comment]
I just wrote the same patch https://github.com/containers/storage/pull/276
LGTM

**Comment by rhatdan** [comment]
@nalind @vrothberg @TomSweeneyRedHat PTAL

**Comment by vrothberg** [comment]
@rh-atomic-bot r+

**Comment by vrothberg** [comment]
Seems the bot doesn't work here? Merging manually :)

**Pull request merged**
