### PR TITLE
graphtest: skip tests on insufficient permissions

### PR DESCRIPTION
**Pull request by mvo5**
Just a quick drive-by while working on https://github.com/containers/storage/issues/1779 - feel free to close if you disagree or feel it's the wrong approach (sorry, I'm new to this codebase) but I wanted to share it for your consideration :)

---

When a graphdriver cannot be tested because of e.g. `ErrIncompatibleFS` it is skipped. However this seems not to be the case for permission error and when running the tests as user they fail with:
```
chown: ... operation not permited
```
This commit changes the test code to account for this as well and skip when there are insufficient permissions.

### CODE REVIEW

**Comment by rhatdan** [comment]
You have to sign your commits

git commit -a --amend -s
git push --force

**Comment by TomSweeneyRedHat** [comment]
reping @mvo5.  Can you tend to the administration as noted by @rhatdan ?

**Comment by mvo5** [comment]
@TomSweeneyRedHat Hey, thanks for the reminder and sorry that I did not reply earlier. I did the force push with the `--amend -s` some days ago, did I do something wrong or miss something?

**Comment by TomSweeneyRedHat** [comment]
@mvo5 Ooops, my bad, I scanned the error too quickly last night and missed your update.  The PR just needed to be updated, which I've just started, and then reviewed.  

LGTM

@edsantiago PTAL

**Pull request merged**
