### PR TITLE
Overlayfs has dropped support for skip_mount_home options

### PR DESCRIPTION
**Pull request by rhatdan**
Remove all references to the option in man pages in default configuration.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @mheon @vrothberg @TomSweeneyRedHat @giuseppe @saschagrunert PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
Why would we document a NOOP.  I think we should add the ignore back to overlay though.

**Comment by vrothberg** [comment]
> Why would we document a NOOP. I think we should add the ignore back to overlay though.

The intention is to communicate it to the user. I wonder if it shouldn't be conditional on the version

**Comment by TomSweeneyRedHat** [comment]
LGTM but lint is kicking up its heals.

**Pull request merged**
