### PR TITLE
cirrus: check cross-compilation

### PR DESCRIPTION
**Pull request by nalind**
Have CI test cross-compiles.

### CODE REVIEW

**Comment by mheon** [comment]
Oh, LGTM - thanks for this, was poking around but wasn't quite able to make it compile.

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @giuseppe @vrothberg PTAL

**Comment by mheon** [comment]
@rhatdan Mind cutting a new tag from this for Buildah + Podman vendoring?

**Comment by rhatdan** [comment]
@mheon I want to get a couple more PRs in, but hopefully soon.

**Pull request merged**
