### PR TITLE
Remove the jsonmessage, pidfile, and sysinfo pkgs

### PR DESCRIPTION
**Pull request by nalind**
We're not using pkg/jsonmessage, pkg/pidfile, or pkg/sysinfo, so this PR removes them.

### CODE REVIEW

**Comment by runcom** [comment]
:+1:

**Comment by rhatdan** [comment]
👍

**Comment by nalind** [comment]
Added pkg/parsers/operatingsystem to the list of removals.  @runcom, @rhatdan, I just want to make sure you're still okay with merging this.

**Comment by runcom** [comment]
if that isn't used either, yeah, I'm okay

**Comment by nalind** [comment]
Great!  Merging.

**Pull request merged**
