### PR TITLE
overlay: force naiveDiff when using a mount program

### PR DESCRIPTION
**Pull request by giuseppe**
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM, but I would prefer a little more description in your PR or why this is necessary.

Something like:
```
Overlay diff relies on the kernel's Overlay driver, if a user specifies an alternative driver, then we need to default back to the naivediff.
```

**Comment by giuseppe** [comment]
Thanks, I've amended your suggestion in the commit message

**Comment by rhatdan** [comment]
LGTM
@nalind @TomSweeneyRedHat @vrothberg @umohnani8 PTAL

**Comment by vrothberg** [comment]
LGTM
Had to wrap my head around the surrounding anonymous function `useNaiveDiffLock.Do(func() {..` first but it looks good to me.

**Pull request merged**
