### PR TITLE
Switch to golang native error wrapping

### PR DESCRIPTION
**Pull request by saschagrunert**
We now use the golang error wrapping format specifier `%w` instead of the deprecated github.com/pkg/errors package.

### CODE REVIEW

**Comment by saschagrunert** [comment]
Ready for review, PTAL @containers/storage-maintainers

**Review by rhatdan — APPROVED** [review]
LGTM
@nalind @giuseppe @vrothberg @flouthoc PTAL

**Comment by rhatdan** [comment]
@giuseppe @flouthoc @vrothberg @nalind @Luap99 PTAL

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by vrothberg — APPROVED** [review]
LGTM

**Comment by vrothberg** [comment]
@saschagrunert could you rebase just to be extra sure we don't miss anything?

Feel free to merge once green.

**Comment by saschagrunert** [comment]
I missed the rebase because of my PTO yesterday, hope nothing broke.

**Pull request merged**
