### PR TITLE
Move lockfile_dawin.go to lockfile_otherunix.go to compile on freebsd

### PR DESCRIPTION
**Pull request by rhatdan**
Files ending in an OS only compile on that os.  We need to have
lockfile_otherunix be used on both MACs and FreeBSD.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Replaces: https://github.com/containers/storage/pull/298

**Comment by rhatdan** [comment]
Closes: https://github.com/containers/storage/issues/297

**Comment by rhatdan** [comment]
@https://github.com/mateuszkwiatkowski PTAL
@giuseppe @TomSweeneyRedHat @nalind PTAL

**Comment by mateuszkwiatkowski** [comment]
@rhatdan Sorry, I couldn't take care of it earlier. Thank you for chiming in. Your change is looking good.

**Pull request merged**
