### PR TITLE
Cirrus: Add initial support for Cirrus-CI

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
***Note to me:*** This is sharing base-images with the libpod project, so need to add meta task using imgts to set last-used-on labels from this project.  Otherwise the base images might get purged.

**Comment by cevich** [comment]
@rhatdan easy part is done PTAL - VMs boot, run commands, and collect logs :smile:   I think I'd prefer to work on the hard-part (VM setup and running tests) via separate PRs.

Note: I did not include CentOS (or RHEL) among the VMs, as they tended to get in the way for libpod being a fast-moving upstream.  Not sure about here. IMHO, it's better to leave the downstream automation to the downstream systems.  But I'll add one/both here if you think they're needed.

**Comment by rhatdan** [comment]
@nalind @TomSweeneyRedHat @vrothberg PTAL

**Comment by rhatdan** [comment]
Nice, LGTM. Now we just need to plum in the tests.
@nalind @giuseppe FYI

**Comment by cevich** [comment]
> LGTM. It's magical!

Please don't unnecessarily over-inflate my ego, it may burst!   TBH, this was mostly a bunch of copy-paste work, and some clicky-clicky on the google cloud web thingie :grin: 

> Now we just need to plum in the tests.

Oooohhhhh, it's more difficult than that I'm afraid.  The next step is to figure out everything that needs to go into ``setup.sh`` for each distro.  Sounds easy, but it can be mind-numbing repetitive.  Unless we get it perfect on the first try, it means re-running the same set of commands over and over and over again.  

@nalind @giuseppe to maintain our sanity, I'll port my `get_ci_vm.sh` script over here from libpod.  This will  let us spin up VMs to play with at will, outside of the CI environment.  We can use these to develop a working `setup.sh` and (later) debug any problems that arise.

**Pull request merged**
