### PR TITLE
storage: fix up docstring comments

### PR DESCRIPTION
**Pull request by cyphar**
In order to make actually reading the interfaces easier (as well as
making godoc actually useful), we need to comment the interface methods
themselves rather than the whole interface.

Signed-off-by: Aleksa Sarai <asarai@suse.de>

### CODE REVIEW

**Comment by nalind** [comment]
Looks good, merging.

**Comment by cyphar** [comment]
Uhh d4ee4f6f488fa2f026e136a95205daec035ee02b isn't a merge, you took my commit then stripped my `Signed-off-by` and my authorship (while also changing the patch slightly). I understand that it's "just" a comment change, but that's not how you merge external contributors' commits -- you're erasing copyright holder information from the repository.

**Comment by nalind** [comment]
Doh.  That's what I get for using git merge instead of the web UI.  Alright if I rewrite the history to try to restore it?

**Comment by nalind** [comment]
Oh, wait, those are two commits.  6a6198a should be exactly what was proposed.

**Comment by cyphar** [comment]
Ah, my apologies. The short message was the same so I didn't think to go through the history (since there wasn't a merge commit). :P

**Comment by nalind** [comment]
No worries.  I'll try to use the web UI to do those in the future.

**Comment by cyphar** [comment]
I actually don't like the Web UI either, but personally I always make sure to use `--no-ff` when using `git merge` because when you fast-forward master then you lose the merge history (this is what the Web UI does by default). If the top commit had been a merge commit I wouldn't have been confused. :P

**Comment by nalind** [comment]
Ah, so that's what I missed.  Thanks for the tip!

**Pull request closed without merging**
