### PR TITLE
Add a ReadOnly field to Layers and Images

### PR DESCRIPTION
**Pull request by nalind**
Add a ReadOnly field to Image and Layer structures, for consumers of the library to use in diagnosing why they can't delete them.

### CODE REVIEW

**Comment by nalind** [comment]
@baude Does this API addition look like what you need?

**Comment by TomSweeneyRedHat** [comment]
Changes LGTM.
I don't think there's an issue if you drop this code on a vm/host that has pre-existing images, but thought I'd ask if it's OK as far as you know.

**Comment by nalind** [comment]
@TomSweeneyRedHat that's the intent, at least.  The new field is neither read from, nor written to, on-disk storage, which makes sense because a given location can be used as read-write storage by one process and read-only storage by another.

**Comment by TomSweeneyRedHat** [comment]
@nalind thanks for the sanity check.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
