### PR TITLE
Fix lint

### LINKED ISSUE #5: Fix lint issues
Here is what I get using #4: 
```
$ make lint
checking lint
cmd/oci-storage/create.go:171::warning: duplicate of cmd/oci-storage/create.go:186-200 (dupl)
cmd/oci-storage/create.go:186::warning: duplicate of cmd/oci-storage/create.go:171-185 (dupl)
cmd/oci-storage/container.go:90::warning: duplicate of cmd/oci-storage/image.go:76-127 (dupl)
cmd/oci-storage/image.go:76::warning: duplicate of cmd/oci-storage/container.go:90-141 (dupl)
cmd/oci-storage/containers.go:1::warning: duplicate of cmd/oci-storage/images.go:1-45 (dupl)
cmd/oci-storage/images.go:1::warning: duplicate of cmd/oci-storage/containers.go:1-45 (dupl)
cmd/oci-storage/delete.go:14::warning: duplicate of cmd/oci-storage/delete.go:44-72 (dupl)
cmd/oci-storage/delete.go:44::warning: duplicate of cmd/oci-storage/delete.go:116-144 (dupl)
cmd/oci-storage/delete.go:116::warning: duplicate of cmd/oci-storage/delete.go:14-42 (dupl)
storage/images.go:268::warning: duplicate of storage/layers.go:501-519 (dupl)
storage/layers.go:501::warning: duplicate of storage/images.go:268-286 (dupl)
pkg/devicemapper/devmapper.go:547::warning: duplicate of pkg/devicemapper/devmapper.go:574-597 (dupl)
pkg/devicemapper/devmapper.go:574::warning: duplicate of pkg/devicemapper/devmapper.go:547-570 (dupl)
storage/store.go:939::warning: duplicate of storage/store.go:1886-1917 (dupl)
storage/store.go:1886::warning: duplicate of storage/store.go:939-970 (dupl)
storage/store.go:1966::warning: duplicate of storage/store.go:2009-2050 (dupl)
storage/store.go:2009::warning: duplicate of storage/store.go:1966-2007 (dupl)
cmd/oci-storage/status.go:1::warning: duplicate of cmd/oci-storage/version.go:1-38 (dupl)
cmd/oci-storage/version.go:1::warning: duplicate of cmd/oci-storage/status.go:1-38 (dupl)
pkg/archive/archive_test.go:820::warning: duplicate of pkg/archive/example_changes.go:82-97 (dupl)
drivers/devmapper/deviceset.go:1737::warning: duplicate of drivers/devmapper/deviceset.go:1770-1800 (dupl)
drivers/devmapper/deviceset.go:1770::warning: duplicate of drivers/devmapper/deviceset.go:1737-1767 (dupl)
make: *** [Makefile:56: lint] Error 1
```

### PR DESCRIPTION
**Pull request by erikh**
This fixes numerous gometalinter (`make lint`) related issues by applying fixes and (sometimes large) necessary refactors.

This is a WIP and will be finished as I get time, which probably means this week. There is plenty to review already, however, if you are so inclined. Most new changes will end up near the end of the commit list.

PTAL

Fixes #5

### CODE REVIEW

**Comment by erikh** [comment]
this also incorporates some other branches, very sorry. this is in no shape for merge yet though.

**Comment by erikh** [comment]
This is ready for review now I think. Note that it currently incorporates #26
and #24 so things will pass.

**Comment by erikh** [comment]
rebased over #26

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by rhatdan** [comment]
@erikh Can you fix up this pull request?

**Comment by erikh** [comment]
this is goign to take quite a bit of effort. We should probably just close
it.

**Pull request closed without merging**
