### PR TITLE
overlay: use `dir` for final `diff`/`merged` dirs

### PR DESCRIPTION
**Pull request by mvo5**
Dan suggested to open this as a PR and I'm happy to do this. For details see my short commit message below and the issue #1779. I did not open a PR initially because I don't have a test for my change (sorry for that!). I hope it's still useful and maybe someone more familiar with the codebase can write a regression test for this change. Feel free to close/rework as needed of course.

---

This commit fixes an issue with the `overlay.go:Driver.get()` code when the requested `id` comes from an extra storage dir that got specified with e.g. `podman --imagestore`. In this scenario the final layer with the `.../diff` dir must come from the extra storage dir instead of from the main storage (that is may not contain this id).

This fixes issue #1779 for my test case and I see no other issues in my "light" testing for the "normal" cases. However I'm not familiar with this code base and this is (of course) an extremly sensitive part of the code so please have a careful look.

More details in https://github.com/containers/storage/issues/1779

### CODE REVIEW

**Comment by mvo5** [comment]
Fwiw, https://github.com/osbuild/osbuild/commit/60238b1fa86c59ae40793a8b091785bc1a4e901b is a testcase for our code in osbuild now to reproduce the issue. It essentially does:
1. build an image with two layers that contain both "/file1" with different content 
2. export this image to a tempdir $tmpstore container storage via skopeo
3. remove it from the podman container storage
4.  run `podman --imagestore $tmpstore image mount` and observe that `/file1` is taken from the base layer and not the expected layer

The unpatched podman fails in the expected way, the patched one works correctly in this testcase.

**Comment by rhatdan** [comment]
You have to sign your commit.
git commit -a --amend -s
git push --force

**Comment by rhatdan** [comment]
@giuseppe @nalind PTAL
I will open a WIP PR against Podman to test this out.

**Comment by giuseppe** [comment]
Do you have a reproducer for the issue you are facing?

Should we fix this condition instead?

```
	if imageStore != "" {
		workDirBase = imageStore
	}
```

and make sure that the correct value is used when `--imagestore` is passed?

**Comment by mvo5** [comment]
> Do you have a reproducer for the issue you are facing?
[..]

I do, it's part of our tests in osbuild, the easiest way is probably to do the following:
```
$ git clone https://github.com/mvo5/osbuild
$ cd osbuild
$ git checkout a7db0c0d6e85d7644c5c98d116fb4a227353ccd6   # part of the osbuild-container-deploy branch
$ sudo pytest -s -vv -k test_container_deploy
```
the relevant test is stages/test/test_container_deploy.py and the code (very small) is stages/org.osbuild.container-deploy

I'm sorry that I did not extract it for easier consumption but I hope it's useful.

**Comment by mvo5** [comment]
[..]
> Should we fix this condition instead?
> 
> ```
> 	if imageStore != "" {
> 		workDirBase = imageStore
> 	}
> ```
> 
> and make sure that the correct value is used when `--imagestore` is passed?

I don't feel qualified to give a good answer here - I will ramble a bit anyway :) My understanding of this code is that `dir` is the place that the `id` comes from so AIUI it should be used for the final path of the overlay. AIUI podman always adds `--imagestore` as an optional store the `id` could come from the "normal" imageStore and the one added via `--imagestore`. But I may be totally off here so take all of this with a grain of salt.

**Comment by giuseppe** [comment]
would it be possible to use just podman commands for the reproducer?

I've tried your script, but I don't understand what is going on behind and what commands are involved

**Comment by mvo5** [comment]
> would it be possible to use just podman commands for the reproducer?
> 
> I've tried your script, but I don't understand what is going on behind and what commands are involved

Sure thing, I put a standalone reproducer into https://github.com/containers/storage/issues/1779#issuecomment-1863419315 - it's still slightly more complicated than I would like, I'm sorry for that, I can give it another attempt tomororw to simply or convert to shell, just let me know :)

**Comment by mvo5** [comment]
Fwiw, the tests in the podman PR in https://github.com/containers/podman/pull/21058 seems to be failing so my changes are too simplistic and/or incorrect. Should we close this again? Or keep it to be able to test changes here?

**Comment by giuseppe** [comment]
we can keep it open if you plan to work more on this.  Otherwise we can close it until we have a minimal reproducer that uses only Podman

**Comment by mvo5** [comment]
> we can keep it open if you plan to work more on this. Otherwise we can close it until we have a minimal reproducer that uses only Podman

I tweaked the change a bit, I was able to run one of the failing tests locally. I also tweaked the reproducer in https://gist.github.com/mvo5/36c35e9d2a17ad56f73aa90970dbbc27 (still pytest though but better output and a bit more linear)

**Comment by giuseppe** [comment]
could you try https://github.com/containers/storage/pull/1784 ?

**Comment by mvo5** [comment]
> could you try #1784 ?

Sure, sorry that it took me so long. I applied #1784 into the vendor tree in podman and build it. The file in my test is now coming from the correct layer \o/ - thank you! However I do see a leftover mount in `/tmp/test-issue1179/overlay`:
```
$ grep overlay /proc/self/mountinfo 
13551 32 259:3 /tmp/test-issue1179/overlay /tmp/test-issue1179/overlay rw,relatime - ext4 /dev/nvme0n1p2 rw,errors=remount-ro
```
I am not sure where this one comes from, iirc my test does not create any bind mounts and I double checked that `podman image umount` is called in my script.

**Comment by mvo5** [comment]
I close this one now given the very nice work in 1784. @giuseppe please let me know if I should copy my comment https://github.com/containers/storage/pull/1781#issuecomment-1866706672 into #1784

**Pull request closed without merging**
