### PR TITLE
Vendor in latest ostree to remove compiler warnings

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe Any idea why this is blowing up.  Works in my local machine.

**Comment by giuseppe** [comment]
bot, retest this please

**Comment by giuseppe** [comment]
could you try to add a patch that drops the `-compiler gc` bit?

**Comment by giuseppe** [comment]
@rhatdan opened this PR in ostree-go: https://github.com/ostreedev/ostree-go/pull/26

I could reproduce the error when using golang 1.8

**Comment by mheon** [comment]
LGTM

**Comment by TomSweeneyRedHat** [comment]
Just curious why "master" instead of a particular id?  Thought we were trying to stay away from master?
Otherwise happy green buttons and LGTM.

**Comment by rhatdan** [comment]
Could have done master, but It was changing regularly.  I think each repo is different.

**Comment by vrothberg** [comment]
The problem with vendoring a branch (in contrast to vendoring a specific commit) is that it makes it hard to reproduce and to debug. The only ways to find out which commit has been vendored is to either check the timestamp (error prone), or to compare hashes (time consuming).

**Comment by rhatdan** [comment]
Yes, understood.

**Pull request merged**
