### PR TITLE
    counter: check for external umounts

### PR DESCRIPTION
**Pull request by rhatdan**
Cherry pick update for back port for podman,

### CODE REVIEW

**Comment by rhatdan** [comment]
@mheon @giuseppe I think this is what you need for podman?

**Comment by mheon** [comment]
I think I already handled the cherry-pick, but we do need a fresh release of v1.20 to clean up the nasty hacks I had to do to the v2.0 branch of Podman

**Comment by TomSweeneyRedHat** [comment]
As @mheon noted, this looks to be a dupe of #700...

**Comment by mheon** [comment]
LGTM

**Pull request merged**
