### PR TITLE
storage: drop ostree deduplication

### PR DESCRIPTION
**Pull request by giuseppe**
it was an attempt to use OSTree to deduplicate files, at the time we already had a dependency on OSTree for system containers in containers/image.  Since the feature never really took off, let's just drop it.

Closes: https://github.com/containers/storage/issues/419
 
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
I am fine with this, although it is API Breakage and we will need to bounce the major version.
LGTM

**Comment by nalind** [comment]
LGTM.  If we're doing a bump, we ended up never using the `ParentOwner` methods, so we might want to drop them as well, as a separate PR.

**Comment by rhatdan** [comment]
SGTM

**Comment by jordemort** [comment]
Would it be unwelcome if I attempted to revive this later in the year, with the intent of using it and maintaining it? I'm working on https://github.com/hello-seam/podracer right now and it mostly wouldn't need to exist if there was an OSTree storage driver.

**Comment by rhatdan** [comment]
We would consider it.

**Pull request merged**
