### PR TITLE
Don’t silently ignore errors when decoding JSON or deleting incomplete layers

### PR DESCRIPTION
**Pull request by mtrmac**
See individual commit messages for details

Cc: @nalind to make sure I’m not missing some error resiliency trade-off.

I’ll run this through Buildah and Podman CI together with some follow-up PRs.

### CODE REVIEW

**Comment by mtrmac** [comment]
Downstream tests (from #1406, a superset):
- https://github.com/containers/buildah/pull/4368
- https://github.com/containers/podman/pull/16253

**Review by vrothberg — COMMENTED** [review]
LGTM

Let's wait for @nalind's head nod before merging.

**Comment by mtrmac** [comment]
Rebased, and added one more commit to avoid more `err == nil` checks.

**Comment by mtrmac** [comment]
I don’t personally have any preference in `%q` vs `%#v`, do you want me to change that to be consistent for layer IDs, one way or another?

**Comment by nalind** [comment]
Nah, it's already in too many places to be worth the churn.

**Pull request merged**
