### PR TITLE
[v1.38, backport] store: add independent `AddNames` and `RemoveNames` for images,layers,containers

### PR DESCRIPTION
**Pull request by flouthoc**
Backport of https://github.com/containers/storage/pull/1153

Adds AddNames and RemoveNames so operations which are invoked in parallel
manner can use it without destroying names from storage.

For instance

We are deleting names which were already written in store.
This creates faulty behavior when builds are invoked in parallel manner, as
this removes names for other builds.

To fix this behavior we must append to already written names and
override if needed. But this should be optional and not break public API

Following patch will be used by parallel operations at podman or buildah end, directly or indirectly.

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM

**Comment by flouthoc** [comment]
nvm its already here: https://github.com/containers/storage/tree/v1.38.3

**Comment by TomSweeneyRedHat** [comment]
Partially addresses: https://bugzilla.redhat.com/show_bug.cgi?id=2066519 and https://bugzilla.redhat.com/show_bug.cgi?id=2055487

**Comment by TomSweeneyRedHat** [comment]
Exceptions approved:  RHEL 9.0 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2066519  RHEL 8.6 BZ: https://bugzilla.redhat.com/show_bug.cgi?id=2055487

**Pull request merged**
