### PR TITLE
lockfile: reshape for multiplatform

### PR DESCRIPTION
**Pull request by vbatts**
this stubs out for having platform-independent file locking

This still functions the same on `GOOS=linux`, and now succeeds for
`GOOS=windows`. But still fails on `freebsd`, `darwin`, `solaris`, etc

Signed-off-by: Vincent Batts <vbatts@hashbangbash.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by nalind** [comment]
This breaks compilation when GOOS=darwin, which is at least expected to work by skopeo.  Moving the version of `TouchedSince()` that's in `lockfile_unix.go` to a file that's built only on `linux` and `solaris`, and changing the build tags on the original file so that it, too, is built for `darwin` and `freebsd` cases, should fix that.  (We'll still have a couple of type mismatches breaking the build for `freebsd`, but it's progress.)

**Comment by vbatts** [comment]
Ok I'll update this. When I tried darwin first it failed, so I wasn't sure
that it was supposed to work in the first place.

**Comment by vbatts** [comment]
updated PTAL

**Comment by nalind** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
