### PR TITLE
[1.20] store: replace Modified+Load with ReloadIfChanged

### PR DESCRIPTION
**Pull request by haircommander**
add a new method to reload the store information from the hard disk if
has changed.
pick of https://github.com/containers/storage/pull/905

Signed-off-by: Giuseppe Scrivano gscrivan@redhat.com
Cherry-picked-by: Peter Hunt pehunt@redhat.com

### CODE REVIEW

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@haircommander Are the test failures expected?

**Comment by haircommander** [comment]
no, maybe CI is out of date?
```
[+0316s] Err:8 http://security.ubuntu.com/ubuntu eoan-security Release
[+0316s]   404  Not Found [IP: 91.189.91.39 80]
```

**Comment by rhatdan** [comment]
Forcing merge.

**Pull request merged**
