### PR TITLE
sync write link and lower files to avoid file corruption caused by poweroff

### PR DESCRIPTION
**Pull request by gaohuatao-1**
When the os is powered off during file writing, the scenario is possible happen that the file exists but it's content is empty.

Signed-off-by: gaohuatao <gaohuatao@huawei.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@giuseppe PTAL

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by giuseppe** [comment]
This is not robust as image files could have been left unsynced.  I suggest to look at what CRI-O does

**Comment by gaohuatao-1** [comment]
> This is not robust as image files could have been left unsynced. I suggest to look at what CRI-O does.
> 
> I'd like we avoid additional `fsync` calls as they slow down I/O and they usually just hide the problem of a corrupted storage.

**Comment by gaohuatao-1** [comment]
@giuseppe sorry, i closed it accidentally

**Comment by giuseppe** [comment]
> @giuseppe Yes, your opinion is reasonable, but it may cause functional problem

the problem I see is that while this gives the impression the storage is not corrupted (and it is an expensive I/O operation), the stored images are likely corrupted.  So you'll end up with random errors at runtime when there are running containers.

**Comment by gaohuatao-1** [comment]
> > @giuseppe Yes, your opinion is reasonable, but it may cause functional problem
> 
> the problem I see is that while this gives the impression the storage is not corrupted (and it is an expensive I/O operation), the stored images are likely corrupted. So you'll end up with random errors at runtime when there are running containers.

This operation does cause I/O to slow down. I recommend to close this PR

**Pull request closed without merging**
