### PR TITLE
fix inconsitent go build tags

### PR DESCRIPTION
**Pull request by Luap99**
Run `go fmt ./...` which automatically adds the new build tag syntax.
This change is backwards compatible.

CI: run make local-validate

Make sure all PRs are formated with `go fmt` correctly.
I added it to the existing lint job as this seems to make the most
sense to me.

### CODE REVIEW

**Comment by rhatdan** [comment]
Lint is broken.

**Comment by Luap99** [comment]
This should good now, the one failure is caused by a CI issue. I do not have permission to restart it here.

**Review by lsm5 — APPROVED** [review]
/lgtm
/hold

**Comment by lsm5** [comment]
looks like it needs a rebase

**Comment by lsm5** [comment]
@rhatdan i think would be nice to get this vendored into podman, buildah, skopeo soon as possible.

**Comment by Luap99** [comment]
@lsm5 did you checked if it fixes your issue?
AFAIK go is still backwards compatible with the old tags so it should at least in theory work even without this PR.

**Comment by lsm5** [comment]
Didn't check prior. Anyway, trying to vendor it now on f37 with golang v1.19.2 and I'm seeing unrelated vendoring issues
```
github.com/containers/podman/v4/cmd/podman/images imports
	github.com/containers/ocicrypt/helpers imports
	github.com/containers/ocicrypt/utils imports
	gopkg.in/square/go-jose.v2: unrecognized import path "gopkg.in/square/go-jose.v2": https fetch: Get "https://gopkg.in/square/go-jose.v2?go-get=1": dial tcp 185.125.188.236:443: i/o timeout
```

I'll spin up a c9s vm in a bit and look further

**Pull request merged**
