### PR TITLE
Remove whitelist and replace with allowed

### PR DESCRIPTION
**Pull request by rhatdan**
We want to remove insensitive terms from the codebase.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @vrothberg @saschagrunert @giuseppe @TomSweeneyRedHat @ashley-cui @QiWang19 PTAL

**Comment by ashley-cui** [comment]
LGTM

**Comment by QiWang19** [comment]
LGTM

**Pull request merged**
