### PR TITLE
Lock file cleanups, notably getLockfile vs. getLockFile naming

### PR DESCRIPTION
**Pull request by mtrmac**
See the individual commit messages for details.

### CODE REVIEW

**Comment by mtrmac** [comment]
NOTE: Although the documentation to `GetLockfile`/`GetROLockfile` could be similarly extended with more details, I stopped at the private implementation helper level, because I don’t think I understand the API / use.

- AFAICS, `GetLockfile(singlePath); GetROLockfile(singlePath)` will fail. Is that intentional, a bug that matters, a bug that does not matter in practice?
- The idea of “read-only lock” that is actually a read-write lock, except that locking for write will _only lock it for read_ is very counter-intuitive to me, and confuses me greatly. Does it have to be like that? I would expect there to be a clear type-system-enforced separation between simple mutexes and R/W locks, and for the R/W locks to have clearly-separated “read {un,}lock” and “write {un,}lock” methods; I find it pretty scary that a `.Lock` call can silently behave as a `RLock` call, depending on the receiver object. Yet, apparently, code does depend on this behavior, and I have no idea whether it would be practical to untangle.

So, this stops at being explicit about what the helpers do, and leaves the public API, its documentation, and its use throughout the package unchanged for whoever understands it already.

**Comment by vrothberg** [comment]
Please defer merging this to after https://github.com/containers/storage/pull/307.

**Comment by rhatdan** [comment]
@mtrmac #307 has been merged can you update your PR?

**Comment by mtrmac** [comment]
Rebased.

**Comment by vrothberg** [comment]
The lockfile tests are flaky. I opened https://github.com/containers/storage/pull/314 to reduce the chance of hitting them. @mtrmac, feel free to pick the commit from there (and change at your wish).

**Comment by vrothberg** [comment]
Changes here LGTM. @nalind @rhatdan PTAL.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
