### PR TITLE
Cirrus: Update VM Images + env. var. name

### PR DESCRIPTION
**Pull request by cevich**
For consistency with CI in other repositories, update the variable name.
Also, remove some variable definitions which are not included in the
common automation library.

Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by cevich** [comment]
@rhatdan or @nalind how do I fix the `github.com/containers/storage/drivers/devmapper` failure?

**Comment by rhatdan** [comment]
@cevich that is a regular flake we have on devmapper testing.

**Comment by rhatdan** [comment]
LGTM

**Comment by cevich** [comment]
Oh ok, thanks.  So I'll just re-run and bury my head in the sand.

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Pull request merged**
