### PR TITLE
Don't fail on walking os of EOPNOTSUPP for Llistxatt

### PR DESCRIPTION
**Pull request by rhatdan**
Fixes: https://github.com/containers/storage/issues/1321

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind @giuseppe @vrothberg @saschagrunert @TomSweeneyRedHat @flouthoc PTAL

**Comment by nalind** [comment]
LGTM.  I was thinking it would be faster to let us break out of `WalkDir()` on the first failure, but we probably do need to continue scanning at least the top-level directory.
Non-blocking: we should just merge `check_116.go` in with the regular `check.go`, since we dropped the 1.15-and-earlier implementation in #1176.

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by saschagrunert — APPROVED** [review]

**Review by vrothberg — APPROVED** [review]
LGTM

**Pull request merged**
