### PR TITLE
zstd: use github.com/klauspost/compress directly

### PR DESCRIPTION
**Pull request by vrothberg**
The DataDog/zstd package added more than 2MB to the binary size.
Reduce that by using the github.com/klauspost/compress directly
from 11MB to 8.7MB.

Signed-off-by: Valentin Rothberg <rothberg@redhat.com>

### CODE REVIEW

**Comment by vrothberg** [comment]
Don't merge. I think we don't need cgo anymore.

**Comment by vrothberg** [comment]
It squeezes the same amount from Podman :+1: 

@baude @mheon FYI

**Comment by vrothberg** [comment]
@giuseppe @nalind PTAL

**Comment by giuseppe** [comment]
LGTM

**Comment by rhatdan** [comment]
LGTM

**Comment by vrothberg** [comment]
@rhatdan, can we cut a new release to revendor it across the stack? Codename: slimfast.

**Pull request merged**
