### PR TITLE
tarlogger: drop state mutex

### PR DESCRIPTION
**Pull request by giuseppe**
detect when the read pipe got closed by using the Write error code.
    
It solves a race, where the pipe could be closed between the check and
the actual write.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
dropped the WIP, pushed a simpler implementation.

**Comment by vrothberg** [comment]
Amazing work, @giuseppe! I believe we have isolated the sources of the two errors; this and the proxy.

**Comment by vrothberg** [comment]
@nalind @rhatdan PTAL

**Comment by rhatdan** [comment]
LGTM
I would like @nalind to give his ok, and then we need to cut a new release.

**Comment by vrothberg** [comment]
@rhatdan let's wait with a new release until after the tests. I'll set some new ones up with this fix. I ran some without the proxy over night on my machine and didn't see any error anymore. We're getting close.

**Comment by vrothberg** [comment]
All tests were successful :heavy_check_mark:

**Comment by nalind** [comment]
LGTM

**Comment by mrunalp** [comment]
Do we need this for CRI-O 1.16 (for 4.3.0) ?

**Comment by vrothberg** [comment]
> Do we need this for CRI-O 1.16 (for 4.3.0) ?

I'd say, yes. I will identify all impacted releases tomorrow and prepare storage releases for CRI-O and Podman.

**Pull request merged**
