### PR TITLE
Add test for bad entries in storage.conf

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @saschagrunert @vrothberg PTAL

**Review by vrothberg — COMMENTED** [review]
LGTM, thank you @rhatdan

**Review by saschagrunert — APPROVED** [review]
/lgtm

**Comment by TomSweeneyRedHat** [comment]
Thx @rhatdan

**Pull request merged**
