### PR TITLE
Separate CI ops for ease of debug/maintenance

### PR DESCRIPTION
**Pull request by cevich**
Signed-off-by: Chris Evich <cevich@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@TomSweeneyRedHat @nalind @vrothberg @giuseppe PTAL

**Comment by cevich** [comment]
> Probably not important here. Since I don't think we will be adding many more extensive tests. I rather spend our time to get an infrastructure like this setup for Buildah.

okay, I'll consolidate the scripts rather than separate.  Keeping things simple and useful for y'all is my goal.  Then I'll copy what's here over to buildah as a starting point...

**Comment by cevich** [comment]
...okay off to buildah land.

**Comment by giuseppe** [comment]
LGTM

**Pull request merged**
