### PR TITLE
Remove old +build tags, add gofix ci job

### PR DESCRIPTION
**Pull request by kolyshkin**
1. Remove old-style `+build` tags (via `go fix`)
2. Add a CI job to ensure `go fix` would not change anything

### CODE REVIEW

**Comment by rhatdan** [comment]
/approve
LGTM

**Comment by rhatdan** [comment]
@nalind @giuseppe @flouthoc @vrothberg @mheon PTAL

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
