### PR TITLE
    Cleanup make vendor code to actualy tidy up repo

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
@giuseppe @vrothberg @nalind @TomSweeneyRedHat PTAL

**Comment by TomSweeneyRedHat** [comment]
LGTM assuming happy tets

**Comment by vrothberg** [comment]
Can we change it to do the same as @mtrmac did for Skopeo (https://github.com/containers/skopeo/commit/1f321dfc696046b98c1e92a4f3ada0545b1e7923)?

**Comment by mtrmac** [comment]
And then `go mod vendor` should probably remain _after_ `go mod tidy`, so that `vendor` clearly matches the _results_ of `tidy`.

**Comment by mtrmac** [comment]
Green buttons everywhere, but I can’t see any evidence of tests running.

**Pull request merged**
