### PR TITLE
Audit and update OWNERS file

### PR DESCRIPTION
**Pull request by baude**
Just performing an audit and cleanup of the OWNERS file.  Cleaned out duplicate reviewer entries as well.  Made judgement calls on the names based on the last 24 months of contributions, etc.

### CODE REVIEW

**Comment by baude** [comment]
Consider this a first attempt; happy to make changes.

**Comment by rhatdan** [comment]
/approve
LGTM

**Review by vrothberg — COMMENTED** [review]
LGTM

@giuseppe PTAL

**Review by giuseppe — APPROVED** [review]
/lgtm

**Pull request merged**
