### PR TITLE
Use containers/image release v1.5 rather then master

### PR DESCRIPTION
**Pull request by rhatdan**
Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by rhatdan** [comment]
Partial fix for https://github.com/containers/storage/issues/293

**Comment by TomSweeneyRedHat** [comment]
LGTM

**Comment by rhatdan** [comment]
@vrothberg @nalind PTAL

**Comment by rhatdan** [comment]
Since https://github.com/containers/storage/pull/299 merged this is irrelevant.

**Pull request closed without merging**
