### PR TITLE
Change Mounted to return the number of times mounted

### PR DESCRIPTION
**Pull request by rhatdan**
podman unmount wants to know if the image is only mounted 1 time
and refuse to unmount if the container state expects it to be mounted.

Signed-off-by: Daniel J Walsh <dwalsh@redhat.com>

### CODE REVIEW

**Comment by mheon** [comment]
Turns out to be a lot more useful for us than just a bool - LGTM

**Comment by TomSweeneyRedHat** [comment]
LGTM and happy green tests.  I smell a quick vendor for Podman

**Comment by rhatdan** [comment]
@nalind PTAL

**Comment by nalind** [comment]
LGTM

**Pull request merged**
