### PR TITLE
Remove Get prefix on method calls.

### PR DESCRIPTION
**Pull request by rhatdan**
Go validate suggests that you should not use functions that begin with Get,
unless you have to.

### CODE REVIEW

**Comment by rhatdan** [comment]
@nalind PTAL, I would like to get this one so it becomes easier to review the others.

**Comment by nalind** [comment]
Looks alright.  While we're making changes to the API that consumers of the library see, I'd like to go ahead and relocate the storage package up a level so that people can stop having to import ".../storage/storage".

**Comment by rhatdan** [comment]
@nalind storage/storage is now just storage.
Sort of like pizza/pizza

**Comment by nalind** [comment]
LGTM pending CI.

**Pull request merged**
