### PR TITLE
Cirrus: Update CI VM Images to F37

### PR DESCRIPTION
**Pull request by cevich**

### CODE REVIEW

**Comment by cevich** [comment]
Force-push: Rebased.

**Comment by rhatdan** [comment]
@giuseppe PTAL

**Comment by cevich** [comment]
force-push: slightly newer images.

**Comment by cevich** [comment]
Same breakage.  @giuseppe help please.  These images pass CI in many/most other repos.  Are the 'overlay' tests still valid for F37 using BTRFS root?  Did I screw something up in the images maybe?

**Comment by giuseppe** [comment]
> Same breakage. @giuseppe help please. These images pass CI in many/most other repos. Are the 'overlay' tests still valid for F37 using BTRFS root? Did I screw something up in the images maybe?

opened a new PR to run some tests: https://github.com/containers/storage/pull/1491

**Pull request closed without merging**
