### PR TITLE
archive: fix createTarFile loses the IMA attribute

### PR DESCRIPTION
**Pull request by yangfeiyu20102011**
archive: fix createTarFile loses the IMA attribute

reason: Lsetxattr the xattrs in the end, because system.Chtimes and other operations
may let the file lose IMA attribute

Signed-off-by: yangfeiyu<yangfeiyu20102011@163.com>

### CODE REVIEW

**Comment by yangfeiyu20102011** [comment]
@rhatdan

**Review by rhatdan — APPROVED** [review]
LGTM

**Comment by rhatdan** [comment]
@saschagrunert @vrothberg @TomSweeneyRedHat @nalind PTAL

**Review by saschagrunert — APPROVED** [review]
Changes LGTM. Is there any way that we can add a test-case to verify that we do not break the behavior in the future again?

**Comment by TomSweeneyRedHat** [comment]
LGTM
but would like a head nod from @vrothberg or @nalind

**Review by vrothberg — COMMENTED** [review]
LGTM

**Pull request merged**
