### PR TITLE
Enable gofumpt

### PR DESCRIPTION
**Pull request by kolyshkin**
~~_This is currently a draft pending #1615 merge._~~

[gofumpt](https://github.com/mvdan/gofumpt) is a superset of gofmt, enabling some more code formatting rules.

This PR:
 * formats sources with gofumpt;
 * enables gofumpt linter for golangci-lint;
 * removes hack/gofmt.sh (no longer needed).

### CODE REVIEW

**Comment by rhatdan** [comment]
LGTM
@nalind @giuseppe @mtrmac @saschagrunert @umohnani8 @vrothberg PTAL

**Comment by nalind** [comment]
LGTM.  The removal of blank lines from the beginning and ending of blocks is giving me life.

**Comment by rhatdan** [comment]
Needs a rebase.

**Comment by mtrmac** [comment]
(Of all the linters to possibly enable, this one would not be first on my personal list…)

One downside is that using the non-default formatter will be an extra step to deal with for occasional contributors. OTOH PRs to this repo are _comparatively_ rarer than for e.g. Podman.

**Comment by kolyshkin** [comment]
Rebased.

Yes, this linter might be too strict at times, but every change it makes is for the good.

As for contributors, I've added `lint-fix` target to the Makefile, which should fix things up. Alternatively, they can run

```
go install mvdan.cc/gofumpt@latest
gofumpt -w .
```

(provided `$GOPATH/bin` is in `$PATH`).

**Pull request merged**
